//
//  BookListDataModel.m
//  Sefaria
//
//  Created by MGM on 7/14/14.
//  Copyright (c) 2014 Test. All rights reserved.
//

#import "BookListDataModel.h"

@implementation BookListDataModel

@synthesize theCompleteDictionary=_theCompleteDictionary,theCategoryList=_theCategoryList,theCompleteTextArray=_theCompleteTextArray;

#define DK 2
#define LOG if(DK == 1)

+ (BookListDataModel*) myNewDataLoader: (NSString*) filePathStringFromArray
{
    BookListDataModel* myTextDataModel = [[BookListDataModel alloc]init];
    
    NSString* fullString = [NSString stringWithFormat:@"TextData/%@",filePathStringFromArray];
    
    
    NSString *filePath = [[NSBundle mainBundle] pathForResource: fullString ofType:@"json"];
    NSData *myData = [NSData dataWithContentsOfFile:filePath];
    
    
    if (myData == nil) {
        NSLog(@"-- Error - FS %@ --",fullString);
        NSLog(@"nil data");
    }
    
    //
    // NSJSONSerialization
    //
    NSError* error;
    myTextDataModel.theCompleteDictionary = [NSJSONSerialization JSONObjectWithData:myData
                                                                            options:kNilOptions
                                                                              error:&error];

    //
    // The Text
    //

    if ([myTextDataModel.theCompleteDictionary objectForKey:@"text"]) {
        myTextDataModel.theCompleteTextArray = [myTextDataModel.theCompleteDictionary objectForKey:@"text"];
        LOG NSLog(@"-- Full Text: %@ --",myTextDataModel.theCompleteTextArray);
    }
    else {
        LOG NSLog(@"Text Error");
        LOG NSLog(@"-- FullPath: %@ --",filePathStringFromArray);
        LOG NSLog(@"-- --");
    }
    
    //
    // Titles
    //
    if ([myTextDataModel.theCompleteDictionary objectForKey:@"title"]) {
        myTextDataModel.theTitle = [myTextDataModel.theCompleteDictionary objectForKey:@"title"];
        LOG NSLog(@"-- Title: %@ --",[myTextDataModel.theCompleteDictionary objectForKey:@"title"]);
    }
    else {
        LOG NSLog(@"Error for English Title");
        LOG NSLog(@"-- FullPath: %@ --",[myTextDataModel.theCompleteDictionary objectForKey:@"title"]);
        LOG NSLog(@"-- --");
    }
    
    if ([myTextDataModel.theCompleteDictionary objectForKey:@"heTitle"]) {
        myTextDataModel.theHebrewTitle = [myTextDataModel.theCompleteDictionary objectForKey:@"heTitle"];
        LOG NSLog(@"-- Hebrew Title: %@ --",[myTextDataModel.theCompleteDictionary objectForKey:@"heTitle"]);
    }
    else {
        LOG NSLog(@"Error for Hebrew Title");
        LOG NSLog(@"-- FullPath: %@ --",filePathStringFromArray);
        LOG NSLog(@"-- --");
    }
    return myTextDataModel;
}

- (NSArray*) superTextList
{
    return @[
         @"Chasidut/Ba'al Shem Tov on the Torah/English/Sefaria Community Translation",
         @"Chasidut/Chiddushei HaRim Al HaTorah/English/Sefaria Community Translation",
         @"Chasidut/Chiddushei HaRim Al HaTorah/Hebrew/פרשת בראשית",
         @"Chasidut/Derekh Mitsvotekha/Hebrew/Wikisource",
         @"Chasidut/Kedushat Levi/English/Sefaria Community Translation",
         @"Chasidut/Kedushat Levi/Hebrew/2007 printing",
         @"Chasidut/Me'or Einayim/English/Sefaria Community Translation",
         @"Chasidut/Mekor Mayyim Hayyim/English/Sefaria Community Translation",
         @"Chasidut/Panim yafot/English/Sefaria Community Translation",
         @"Chasidut/Sefer Shel Benonim/English/chabad.org",
         @"Chasidut/Sefer Shel Benonim/Hebrew/he.wikisource.org",
         @"Chasidut/Tanya/English/chabad.org",
         @"Chasidut/Tanya/English/Sefaria Community Translation",
         @"Chasidut/Tanya/Hebrew/chabad.org",
         @"Chasidut/Tanya/Hebrew/Original",
         @"Chasidut/Tanya/Hebrew/wikisource.org",
         
         @"Halakhah/Arbaah Turim/English/Sefaria Community Translation",
         @"Halakhah/Arbaah Turim/English/Warsaw 1861",
         @"Halakhah/Arbaah Turim/English/טור - יורה דעה ב",
         @"Halakhah/Arbaah Turim/Hebrew/Bar Ilan Responsa Project",
         @"Halakhah/Arbaah Turim/Hebrew/OnYourWay",
         @"Halakhah/Arbaah Turim/Hebrew/Warsaw 1861",
         @"Halakhah/Arbaah Turim/Hebrew/ארבעה טורים ב, ה",
         @"Halakhah/Arbaah Turim/Hebrew/ארבעה טורים ב, ו",
         @"Halakhah/Arbaah Turim/Hebrew/ארבעה טורים ב, ז",
         @"Halakhah/Arbaah Turim/Hebrew/ארבעה טורים ב, ח",
         @"Halakhah/Arbaah Turim/Hebrew/ארבעה טורים ב, ט",
         @"Halakhah/Arbaah Turim/Hebrew/ארבעה טורים ב, טו",
         @"Halakhah/Arbaah Turim/Hebrew/ארבעה טורים ב, טז",
         @"Halakhah/Arbaah Turim/Hebrew/ארבעה טורים ב, י",
         @"Halakhah/Arbaah Turim/Hebrew/ארבעה טורים ב, יא",
         @"Halakhah/Arbaah Turim/Hebrew/ארבעה טורים ב, יב",
         @"Halakhah/Arbaah Turim/Hebrew/ארבעה טורים ב, יג",
         @"Halakhah/Arbaah Turim/Hebrew/ארבעה טורים ב, יד",
         @"Halakhah/Arbaah Turim/Hebrew/ארבעה טורים ב, כח",
         @"Halakhah/Arbaah Turim/Hebrew/טור - יורה דעה ב",
         @"Halakhah/Arbaah Turim/Hebrew/טור",
         @"Halakhah/Aruch HaShulchan/English/Wikisource",
         @"Halakhah/Aruch HaShulchan/Hebrew/he.wikisource.org",
         @"Halakhah/Aruch HaShulchan/Hebrew/Wikisource Aruch HaShulchan",
         @"Halakhah/Aruch HaShulchan/Hebrew/Wikisource",
         @"Halakhah/Be'er Mayim Chaim/English/Sefaria Community Translation",
         @"Halakhah/Be'er Mayim Chaim/Hebrew/Published by Gross Bros.",
         @"Halakhah/Ben Ish Hai/English/Sefaria Community Translation",
         @"Halakhah/Ben Ish Hai/English/Wikisource",
         @"Halakhah/Ben Ish Hai/Hebrew/Bereishis",
         @"Halakhah/Ben Ish Hai/Hebrew/Wikisource",
         @"Halakhah/Chofetz Chaim/English/Sefaria Community Translation",
         @"Halakhah/Chofetz Chaim/Hebrew/Published by Gross Brothers, Brooklyn, 1989",
         @"Halakhah/Chofetz Chaim/Hebrew/Published by Gross Brothers., Brooklyn, 1989",
         @"Halakhah/Kitzur Shulchan Aruch/English/Sefaria Community Translation",
         @"Halakhah/Kitzur Shulchan Aruch/English/Yona Newman Translation",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 10",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 11",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 12",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 13",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 14",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 15",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 16",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 17",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 18",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 19",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 20",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 21",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 22",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 221",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 23",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 24",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 25",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 26",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 27",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 28",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 29",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 30",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 31",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 32",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 33",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 34",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 35",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 36",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 37",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 38",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 39",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 4",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 40",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 41",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 42",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 43",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 44",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 45",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 46",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 47",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 49",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 5",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 50",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 6",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 7",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 8",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Chapter 9",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Kizur Shulhan Aruch",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/On Your Way",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Perek 48",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/The Kleinman Edition",
         @"Halakhah/Kitzur Shulchan Aruch/Hebrew/Wikisource Kitzur Shulchan Aruch - Menukad",
         @"Halakhah/Kolbo/English/Sefaria Community Translation",
         @"Halakhah/Maaseh Rav/English/Wikisource",
         @"Halakhah/Maaseh Rav/Hebrew/Wikisource",
         @"Halakhah/Magen Avraham/English/Hadar Egalitarianism Tshuva",
         @"Halakhah/Magen Avraham/English/Sefaria Community Translation",
         @"Halakhah/Magen Avraham/Hebrew/Hadar Egalitarianism Tshuva",
         @"Halakhah/Mishna Berura/English/Sefaria Community Translation",
         @"Halakhah/Mishna Berura/Hebrew/Wikitext",
         @"Halakhah/Mishneh Berurah/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Introduction/Mishneh Torah, Negative Mitzvot/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Introduction/Mishneh Torah, Overview of Mishneh Torah Contents/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Introduction/Mishneh Torah, Overview of Mishneh Torah Contents/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Introduction/Mishneh Torah, Positive Mitzvot/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Introduction/Mishneh Torah, Transmission of the Oral Law/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Introduction/Mishneh Torah, Transmission of the Oral Law/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, Blessings/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, Circumcision/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, Fringes/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, Prayer and the Priestly Blessing/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, Prayer and the Priestly Blessing/Hebrew/just the first two halachot",
         @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, Prayer and the Priestly Blessing/Hebrew/Mechon Mamre",
         @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, Prayer and the Priestly Blessing/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, Prayer and the Priestly Blessing/Hebrew/Wikisource",
         @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, Reading the Shema/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, Reading the Shema/English/The Book of Love",
         @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, Reading the Shema/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, Tefillin, Mezuzah and the Torah Scroll/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, The Order of Prayer/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Avodah/Mishneh Torah, Admission into the Sanctuary/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Avodah/Mishneh Torah, Daily Offerings and Additional Offerings/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Avodah/Mishneh Torah, Sacrifices Rendered Unfit/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Avodah/Mishneh Torah, Sacrificial Procedure/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Avodah/Mishneh Torah, Service on the Day of Atonement/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Avodah/Mishneh Torah, The Chosen Temple/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Avodah/Mishneh Torah, Things Forbidden on the Alter/Hebrew/chabad.org",
         @"Halakhah/Mishneh Torah/Sefer Avodah/Mishneh Torah, Things Forbidden on the Alter/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Avodah/Mishneh Torah, Trespass/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Avodah/Mishneh Torah, Vessels of the Sanctuary and Those who Serve Therein/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Haflaah/Mishneh Torah, Appraisals and Devoted Property/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Haflaah/Mishneh Torah, Nazariteship/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Haflaah/Mishneh Torah, Oaths/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Haflaah/Mishneh Torah, Vows/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Kedushah/Mishneh Torah, Forbidden Foods/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Kedushah/Mishneh Torah, Forbidden Intercourse/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Sefer Kedushah/Mishneh Torah, Forbidden Intercourse/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Kedushah/Mishneh Torah, Ritual Slaughter/English/Copy for Education",
         @"Halakhah/Mishneh Torah/Sefer Kedushah/Mishneh Torah, Ritual Slaughter/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Sefer Kedushah/Mishneh Torah, Ritual Slaughter/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Kinyan/Mishneh Torah, Agents and Partners/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Kinyan/Mishneh Torah, Neighbors/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Kinyan/Mishneh Torah, Ownerless Property and Gifts/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Kinyan/Mishneh Torah, Sales/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Kinyan/Mishneh Torah, Slaves/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Korbanot/Mishneh Torah, Festival Offering/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Korbanot/Mishneh Torah, Firstlings/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Korbanot/Mishneh Torah, Offerings for Those with Incomplete Atonement/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Korbanot/Mishneh Torah, Offerings for Unintentional Transgressions/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Korbanot/Mishneh Torah, Paschal Offering/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Korbanot/Mishneh Torah, Substitution/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Foreign Worship and Customs of the Nations/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Foreign Worship and Customs of the Nations/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Foundations of the Torah/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Foundations of the Torah/English/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Foundations of the Torah/Hebrew/ מִשְׁנֶה תּוֹרָה",
         @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Foundations of the Torah/Hebrew/Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Foundations of the Torah/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Foundations of the Torah/Hebrew/הלכות יסודי התורה פרק שלישי",
         @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Human Dispositions/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Human Dispositions/English/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Human Dispositions/Hebrew/Wikisource Mishneh Torah - Hebrew",
         @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Human Dispositions/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Repentance/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Repentance/Hebrew/Sefer HaMadda Hilchot Teshuva Chapter 1",
         @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Repentance/Hebrew/Sefer HaMadda Hilchot Teshuva Chapter 2",
         @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Repentance/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Torah Study/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Torah Study/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Mishpatim/Mishneh Torah, Borrowing and Deposit/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Mishpatim/Mishneh Torah, Creditor and Debtor/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Mishpatim/Mishneh Torah, Hiring/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Mishpatim/Mishneh Torah, Inheritances/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Mishpatim/Mishneh Torah, Plaintiff and Defendant/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Nashim/Mishneh Torah, Divorce/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Nashim/Mishneh Torah, Levirate Marriage and Release/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Nashim/Mishneh Torah, Marriage/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Sefer Nashim/Mishneh Torah, Marriage/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Nashim/Mishneh Torah, Virgin Maiden/Hebrew/Mechon Mamre",
         @"Halakhah/Mishneh Torah/Sefer Nashim/Mishneh Torah, Virgin Maiden/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Nashim/Mishneh Torah, Woman Suspected of Infidelity/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Sefer Nashim/Mishneh Torah, Woman Suspected of Infidelity/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Nezikim/Mishneh Torah, Damages to Property/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Nezikim/Mishneh Torah, Murderer and the Preservation of Life/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Sefer Nezikim/Mishneh Torah, Murderer and the Preservation of Life/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Nezikim/Mishneh Torah, One Who Injures a Person or Property/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Nezikim/Mishneh Torah, Robbery and Lost Property/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Nezikim/Mishneh Torah, Theft/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Sefer Nezikim/Mishneh Torah, Theft/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Shoftim/Mishneh Torah, Kings and Wars/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Shoftim/Mishneh Torah, Mourning/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Shoftim/Mishneh Torah, Rebels/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Shoftim/Mishneh Torah, Testimony/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Sefer Shoftim/Mishneh Torah, Testimony/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Shoftim/Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Taharah/Mishneh Torah, Defilement by a Corpse/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Taharah/Mishneh Torah, Defilement by Leprosy/English/ner leelef",
         @"Halakhah/Mishneh Torah/Sefer Taharah/Mishneh Torah, Defilement by Leprosy/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Sefer Taharah/Mishneh Torah, Defilement by Leprosy/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Taharah/Mishneh Torah, Defilement of Foods/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Taharah/Mishneh Torah, Immersion Pools/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Taharah/Mishneh Torah, Other Sources of Defilement/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Taharah/Mishneh Torah, Red Heifer/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Taharah/Mishneh Torah, Those Who Defile Bed or Seat/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Taharah/Mishneh Torah, Vessels/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Eruvin/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Fasts/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Leavened and Unleavened Bread/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Leavened and Unleavened Bread/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Rest on a Holiday/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Rest on a Holiday/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Rest on the Tenth of Tishrei/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Sabbath/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Sanctification of the New Month/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Scroll of Esther and Hanukkah/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Scroll of Esther and Hanukkah/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Sheqel Dues/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Shofar, Sukkah and Lulav/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Zeraim/Mishneh Torah, Diverse Species/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Zeraim/Mishneh Torah, First Fruits and other Gifts to Priests Outside the Sanctuary/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Sefer Zeraim/Mishneh Torah, First Fruits and other Gifts to Priests Outside the Sanctuary/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Zeraim/Mishneh Torah, Gifts to the Poor/English/Sefaria Community Translation",
         @"Halakhah/Mishneh Torah/Sefer Zeraim/Mishneh Torah, Gifts to the Poor/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Zeraim/Mishneh Torah, Heave Offerings/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Zeraim/Mishneh Torah, Sabbatical Year and the Jubilee/Hebrew/Rambam",
         @"Halakhah/Mishneh Torah/Sefer Zeraim/Mishneh Torah, Sabbatical Year and the Jubilee/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Zeraim/Mishneh Torah, Second Tithes and Fourth Year's Fruit/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Mishneh Torah/Sefer Zeraim/Mishneh Torah, Tithes/Hebrew/Wikisource Mishneh Torah",
         @"Halakhah/Sefer HaChinukh/English/Sefaria Community Translation",
         @"Halakhah/Sefer HaChinukh/Hebrew/Sefer HaChinukh -- Torat Emet",
         @"Halakhah/Sefer HaChinukh/Hebrew/Sefer HaHinnuch",
         @"Halakhah/Shulchan Aruch HaRav/English/Sefaria Community Translation",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Choshen Mishpat/English/Sefaria Community Translation",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Choshen Mishpat/Hebrew/Torat Emet Freeware Shulchan Aruch",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Choshen Mishpat/Hebrew/Wikisource Shulchan Aruch",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Even HaEzer/English/Sefaria Community Translation",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Even HaEzer/English/Wikisource English Shulchan Aruch",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Even HaEzer/English/Wikisource Shulchan Aruch",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Even HaEzer/Hebrew/Siman 17-11 removed",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Even HaEzer/Hebrew/Torat Emet Freeware Shulchan Aruch",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Even HaEzer/Hebrew/Wikisource Shulchan Aruch",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Orach Chayyim/English/Init",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Orach Chayyim/English/Sefaria Community Translation",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Orach Chayyim/English/TranslationShulchan AruchOrach Chaim10",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Orach Chayyim/English/Wikisource Shulchan Aruch - English",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Orach Chayyim/English/Wikisource Shulchan Aruch",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Orach Chayyim/Hebrew/Mishna Berura Warsaw 1884",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Orach Chayyim/Hebrew/Torat Emet Freeware Shulchan Aruch",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Orach Chayyim/Hebrew/Wikisource Shulchan Aruch",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Yoreh De'ah/English/Sefaria Community Translation",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Yoreh De'ah/English/Wikisource Shulchan Aruch - English",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Yoreh De'ah/Hebrew/Bar Ilan Shulchan Aruch",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Yoreh De'ah/Hebrew/Torat Emet Freeware Shulchan Aruch",
         @"Halakhah/Shulchan Arukh/Shulchan Arukh, Yoreh De'ah/Hebrew/Wikisource Shulchan Aruch",
         @"Halakhah/Yalkut Yosef/English/Sefaria Community Translation",
         
         @"Kabbalah/Be'ur Eser S'firot/English/Sefaria Community Translation",
         @"Kabbalah/Be'ur Eser S'firot/Hebrew/   ביאור עשר ספירות להרב עזריאל מגירונה זל, על דרך שאלה ותשובה",
         @"Kabbalah/Be'ur Eser S'firot/Hebrew/  ביאור עשר ספירות להרב עזריאל מגירונה זל, על דרך שאלה ותשובה",
         @"Kabbalah/Be'ur Eser S'firot/Hebrew/ ביאור עשר ספירות להרב עזריאל מגירונה זל, על דרך שאלה ותשובה",
         @"Kabbalah/Be'ur Eser S'firot/Hebrew/ביאור עשר ספירות להרב עזריאל מגירונה זל, על דרך שאלה ותשובה ",
         @"Kabbalah/Be'ur Eser S'firot/Hebrew/ביאור עשר ספירות להרב עזריאל מגירונה זל, על דרך שאלה ותשובה",
         @"Kabbalah/Pardes Rimonim/Hebrew/1548. Ramak, Rabbi Moshe Cordovero",
         @"Kabbalah/Sefer HaBahir/Hebrew/Wikisource Sefer HaBahir",
         @"Kabbalah/Sefer HaQanah/Hebrew/same",
         @"Kabbalah/Sefer HaQanah/Hebrew/Sefer ha-kana. Práce neznámého autora ze 14. století pravděpodobně toho, který napsal též Sefer ha-pelija.",
         @"Kabbalah/Sefer Yetzirah/English/Sefer Yetzirah The Book of Creation",
         @"Kabbalah/Sefer Yetzirah/Hebrew/Sefer Yetzirah The Book of Creation",
         @"Kabbalah/Zohar/English/Sefaria Community Translation",
         @"Kabbalah/Zohar/English/wikisource.org",
         @"Kabbalah/Zohar/Hebrew/Wikisource",
         @"Kabbalah/Zohar/Hebrew/wikisource.org",
         @"Kabbalah/Zohar/Hebrew/Zohar",
         
         @"Liturgy/Hadran/Hebrew/Wikipedia Hadran",
         @"Liturgy/Pesach Haggadah/English/HAGGADA FOR PESACH ACCORDING TO CHABAD-LUBAVITCH CUSTOM",
         @"Liturgy/Pesach Haggadah/English/Sefaria Community Translation",
         @"Liturgy/Pesach Haggadah/English/The Schechter Haggadah Art, History, and Commentary, by Dr. Joshua Kulp and Professor David Golinkin",
         @"Liturgy/Pesach Haggadah/Hebrew/Passover Haggadah",
         @"Liturgy/Pesach Haggadah/Hebrew/Pesach Haggadah",
         @"Liturgy/Siddur/Ana v'choach/Hebrew/אנא בכח",
         @"Liturgy/Siddur/Shalom Alechem/English/Sefaria Community Translation",
         @"Liturgy/Siddur/Shalom Alechem/Hebrew/Shalom Alechem",
         @"Liturgy/Siddur/Weekday Siddur Ashkenaz/Hebrew/תפילות השחר",
         @"Liturgy/Siddur/Yedid Nefesh/Hebrew/Original version",
         
         @"Midrash/Bemidbar Rabbah/English/Sefaria Community Translation",
         @"Midrash/Bemidbar Rabbah/Hebrew/Daat Bemidbar Rabbah",
         @"Midrash/Bereishit Rabbah/English/Genesis Rabbah 118",
         @"Midrash/Bereishit Rabbah/English/Genesis Rabbah 755",
         @"Midrash/Bereishit Rabbah/English/JTS",
         @"Midrash/Bereishit Rabbah/English/R. Judah's letter to Rome",
         @"Midrash/Bereishit Rabbah/English/Sefaria Community Translation",
         @"Midrash/Bereishit Rabbah/English/Soncino Midrash",
         @"Midrash/Bereishit Rabbah/Hebrew/a",
         @"Midrash/Bereishit Rabbah/Hebrew/Bereishit Rabbah",
         @"Midrash/Bereishit Rabbah/Hebrew/Daat Bereshit Rabbah",
         @"Midrash/Bereishit Rabbah/Hebrew/Genesis Rabbah 755",
         @"Midrash/Bereishit Rabbah/Hebrew/Sefaria Bereishit Rabbah",
         @"Midrash/Bereishit Rabbah/Hebrew/Sefaria Translation",
         @"Midrash/Bereishit Rabbah/Hebrew/Wikisource Bereshit Rabbah",
         @"Midrash/Bereishit Rabbah/Hebrew/wikisource",
         @"Midrash/Devarim Rabbah/English/Sefaria Community Translation",
         @"Midrash/Devarim Rabbah/Hebrew/Daat Devarim Rabbah",
         @"Midrash/Eichah Rabbah/English/Sefaria Community Translation",
         @"Midrash/Eichah Rabbah/Hebrew/Daat Eichah Rabbah",
         @"Midrash/Ein Yaakov/Hebrew/Ein Yaakov -- Daat version",
         @"Midrash/Ein Yaakov/Hebrew/Ein Yaakov Massechet 2 -- Daat version",
         @"Midrash/Esther Rabbah/English/Sefaria Community Translation",
         @"Midrash/Esther Rabbah/Hebrew/Daat Esther Rabbah",
         @"Midrash/Kohelet Rabbah/English/Jewish Environmentalism An Ancient Value Source Sheet, by Adam Rossano, To whom does the world belong and what is our relation to it - The environmentalist imperative in the Midrash",
         @"Midrash/Kohelet Rabbah/Hebrew/Daat Kohelet Rabbah",
         @"Midrash/Legends of the Jews/English/The Legends of the Jews  By Louis Ginzberg  [1909]  ",
         @"Midrash/Legends of the Jews/English/The Legends of the Jews  By Louis Ginzberg  [1909]",
         @"Midrash/Legends of the Jews/English/The Legends of the Jews By Louis Ginzberg [1909]",
         @"Midrash/Mekhilta/English/Mekhilta -- Wikisource",
         @"Midrash/Mekhilta/Hebrew/Mekhilta -- Da'at",
         @"Midrash/Mekhilta/Hebrew/Mekhilta -- Wikisource",
         @"Midrash/Midrash on Proverbs/English/Midrash on Psalms Buber Melody 1",
         @"Midrash/Midrash on Proverbs/English/Sefaria Community Translation",
         @"Midrash/Midrash on Proverbs/Hebrew/Bar Ilan Responsa",
         @"Midrash/Midrash on Proverbs/Hebrew/Midrash on Psalms Buber Melody 1",
         @"Midrash/Midrash Tanchuma/English/Sefaria Community Translation",
         @"Midrash/Midrash Tanchuma/Hebrew/Acharei Mos Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Balak Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Bamidbar Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Bechukosai Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Beha'aloscha Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Behar Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Bereishis Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Beshalach Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Bo Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Chayei Sarah Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Chukas Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Devarim Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Eikev Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Emor Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Haazinu Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Kedoshim",
         @"Midrash/Midrash Tanchuma/Hebrew/Ki Savo Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Ki Seitzei Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Ki Sisa Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Korach Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Lech Lecha Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Masai Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Matos Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Metzora Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Mikeitz Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Mishpatim Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Naso Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Nitzavim Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Noach Tanchumna",
         @"Midrash/Midrash Tanchuma/Hebrew/Pekudei Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Pinchas Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Re'eh Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Shelach Lecha Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Shemini Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Shemos Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Shoftim Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Tazria Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Terumah Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Tetzave Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Toldos Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Tzav Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/V'zos Haberacha Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Vaera Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Vaeschanan Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Vayakhel Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Vayechi Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Vayelech Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Vayeshev Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Vayetze Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Vayigash Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Vayikra Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Vayira Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Vayishlach Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Wikisource Midrash Tanchuma",
         @"Midrash/Midrash Tanchuma/Hebrew/Yisro Tanchuma",
         @"Midrash/Midrash Tehilim/English/Book of Legends",
         @"Midrash/Pesikta de rav kahana /English/Sefaria Community Translation",
         @"Midrash/Rut Rabba/Hebrew/Daat Rut Rabbah",
         @"Midrash/Shemot Rabbah/English/Sefaria Community Translation",
         @"Midrash/Shemot Rabbah/Hebrew/Daat Shemot Rabbah",
         @"Midrash/Shemot Rabbah/Hebrew/Shemot Rabbah",
         @"Midrash/Shir HaShirim Rabbah/Hebrew/Daat Shir Hashirim Rabbah",
         @"Midrash/Vayikra Rabbah/English/Sefaria Community Translation",
         @"Midrash/Vayikra Rabbah/Hebrew/Daat Vayikra Rabbah",
         
         @"Mishnah/Seder Kodashim/Mishnah Arakhin/English/Mishnah Yomit, Joshua Kulp",
         @"Mishnah/Seder Kodashim/Mishnah Arakhin/English/Sefaria Community Translation",
         @"Mishnah/Seder Kodashim/Mishnah Arakhin/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Kodashim/Mishnah Bekhorot/English/Sefaria Community Translation",
         @"Mishnah/Seder Kodashim/Mishnah Bekhorot/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Kodashim/Mishnah Bekhorot/Hebrew/מסכת בכורות פרק א",
         @"Mishnah/Seder Kodashim/Mishnah Chullin/English/Eighteen Treatises from the Mishna",
         @"Mishnah/Seder Kodashim/Mishnah Chullin/English/Sefaria Community Translation",
         @"Mishnah/Seder Kodashim/Mishnah Chullin/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Kodashim/Mishnah Keritot/English/Open Mishna",
         @"Mishnah/Seder Kodashim/Mishnah Keritot/English/Sefaria Community Translation",
         @"Mishnah/Seder Kodashim/Mishnah Keritot/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Kodashim/Mishnah Kinnim/English/Open Mishna",
         @"Mishnah/Seder Kodashim/Mishnah Kinnim/English/Sefaria Community Translation",
         @"Mishnah/Seder Kodashim/Mishnah Kinnim/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Kodashim/Mishnah Meilah/English/Sefaria Community Translation",
         @"Mishnah/Seder Kodashim/Mishnah Meilah/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Kodashim/Mishnah Menachot/English/Sefaria Community Translation",
         @"Mishnah/Seder Kodashim/Mishnah Menachot/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Kodashim/Mishnah Middot/English/Sefaria Community Translation",
         @"Mishnah/Seder Kodashim/Mishnah Middot/Hebrew/Torah DB Mishna",
         @"Mishnah/Seder Kodashim/Mishnah Middot/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Kodashim/Mishnah Tamid/English/Open Mishna",
         @"Mishnah/Seder Kodashim/Mishnah Tamid/English/Sefaria Community Translation",
         @"Mishnah/Seder Kodashim/Mishnah Tamid/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Kodashim/Mishnah Temurah/English/Sefaria Community Translation",
         @"Mishnah/Seder Kodashim/Mishnah Temurah/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Kodashim/Mishnah Zevachim/English/Sefaria Community Translation",
         @"Mishnah/Seder Kodashim/Mishnah Zevachim/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Moed/Mishnah Beitzah/English/Open Mishna",
         @"Mishnah/Seder Moed/Mishnah Beitzah/English/Sefaria Community Translation",
         @"Mishnah/Seder Moed/Mishnah Beitzah/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Moed/Mishnah Chagigah/English/Open Mishna",
         @"Mishnah/Seder Moed/Mishnah Chagigah/English/Sefaria Community Translation",
         @"Mishnah/Seder Moed/Mishnah Chagigah/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Moed/Mishnah Eruvin/English/Eighteen Treatises from the Mishna",
         @"Mishnah/Seder Moed/Mishnah Eruvin/English/Open Mishna",
         @"Mishnah/Seder Moed/Mishnah Eruvin/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Moed/Mishnah Megillah/English/Eighteen Treatises from the Mishna",
         @"Mishnah/Seder Moed/Mishnah Megillah/English/Sefaria Community Translation",
         @"Mishnah/Seder Moed/Mishnah Megillah/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Moed/Mishnah Moed Katan/English/Eighteen Treatises from the Mishna",
         @"Mishnah/Seder Moed/Mishnah Moed Katan/English/Sefaria Community Translation",
         @"Mishnah/Seder Moed/Mishnah Moed Katan/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Moed/Mishnah Pesachim/English/Eighteen Treatises from the Mishna",
         @"Mishnah/Seder Moed/Mishnah Pesachim/English/Open Mishna",
         @"Mishnah/Seder Moed/Mishnah Pesachim/English/Sefaria Community Translation",
         @"Mishnah/Seder Moed/Mishnah Pesachim/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Moed/Mishnah Rosh Hashanah/English/Eighteen Treatises from the Mishna",
         @"Mishnah/Seder Moed/Mishnah Rosh Hashanah/English/Open Mishna",
         @"Mishnah/Seder Moed/Mishnah Rosh Hashanah/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Moed/Mishnah Shabbat/English/Eighteen Treatises from the Mishna",
         @"Mishnah/Seder Moed/Mishnah Shabbat/English/Open Mishna",
         @"Mishnah/Seder Moed/Mishnah Shabbat/English/Sefaria Community Translation",
         @"Mishnah/Seder Moed/Mishnah Shabbat/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Moed/Mishnah Shekalim/English/Sefaria Community Translation",
         @"Mishnah/Seder Moed/Mishnah Shekalim/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Moed/Mishnah Sukkah/English/Eighteen Treatises from the Mishna",
         @"Mishnah/Seder Moed/Mishnah Sukkah/English/Open Mishna",
         @"Mishnah/Seder Moed/Mishnah Sukkah/English/Sefaria Community Translation",
         @"Mishnah/Seder Moed/Mishnah Sukkah/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Moed/Mishnah Taanit/English/Eighteen Treatises from the Mishna",
         @"Mishnah/Seder Moed/Mishnah Taanit/English/Rodkinson",
         @"Mishnah/Seder Moed/Mishnah Taanit/English/Sefaria Community Translation",
         @"Mishnah/Seder Moed/Mishnah Taanit/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Moed/Mishnah Yoma/English/Eighteen Treatises from the Mishna",
         @"Mishnah/Seder Moed/Mishnah Yoma/English/Open Mishna",
         @"Mishnah/Seder Moed/Mishnah Yoma/English/Sefaria Community Translation",
         @"Mishnah/Seder Moed/Mishnah Yoma/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Nashim/Mishnah Gittin/English/Eighteen Treatises from the Mishnah",
         @"Mishnah/Seder Nashim/Mishnah Gittin/English/Sefaria Community Translation",
         @"Mishnah/Seder Nashim/Mishnah Gittin/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Nashim/Mishnah Ketubot/English/Eighteen Treatises from the Mishnah",
         @"Mishnah/Seder Nashim/Mishnah Ketubot/English/Sefaria Community Translation",
         @"Mishnah/Seder Nashim/Mishnah Ketubot/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Nashim/Mishnah Kiddushin/English/Open Mishna",
         @"Mishnah/Seder Nashim/Mishnah Kiddushin/English/Sefaria Community Translation",
         @"Mishnah/Seder Nashim/Mishnah Kiddushin/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Nashim/Mishnah Nazir/English/Sefaria Community Translation",
         @"Mishnah/Seder Nashim/Mishnah Nazir/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Nashim/Mishnah Nedarim/English/Open Mishna",
         @"Mishnah/Seder Nashim/Mishnah Nedarim/English/Sefaria Community Translation",
         @"Mishnah/Seder Nashim/Mishnah Nedarim/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Nashim/Mishnah Sotah/English/Sefaria Community Translation",
         @"Mishnah/Seder Nashim/Mishnah Sotah/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Nashim/Mishnah Yevamot/English/Eighteen Treatises from the Mishna, by D. A. Sola and M. J. Raphall, [1843], at sacred-texts.com",
         @"Mishnah/Seder Nashim/Mishnah Yevamot/English/Mishna Yevamot Translation",
         @"Mishnah/Seder Nashim/Mishnah Yevamot/English/Sefaria Community Translation",
         @"Mishnah/Seder Nashim/Mishnah Yevamot/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Nezikin/Mishnah Avodah Zarah/English/Open Mishna",
         @"Mishnah/Seder Nezikin/Mishnah Avodah Zarah/English/Sefaria Community Translation",
         @"Mishnah/Seder Nezikin/Mishnah Avodah Zarah/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Nezikin/Mishnah Bava Batra/English/Sefaria Community Translation",
         @"Mishnah/Seder Nezikin/Mishnah Bava Batra/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Nezikin/Mishnah Bava Kamma/English/Open Mishna",
         @"Mishnah/Seder Nezikin/Mishnah Bava Kamma/English/Sefaria Community Translation",
         @"Mishnah/Seder Nezikin/Mishnah Bava Kamma/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Nezikin/Mishnah Bava Metzia/English/Hyman Goldin 1913 Translation",
         @"Mishnah/Seder Nezikin/Mishnah Bava Metzia/English/Open Mishna",
         @"Mishnah/Seder Nezikin/Mishnah Bava Metzia/English/Sefaria Community Translation",
         @"Mishnah/Seder Nezikin/Mishnah Bava Metzia/Hebrew/Wikisource Mishna menukad",
         @"Mishnah/Seder Nezikin/Mishnah Bava Metzia/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Nezikin/Mishnah Eduyot/English/Sefaria Community Translation",
         @"Mishnah/Seder Nezikin/Mishnah Eduyot/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Nezikin/Mishnah Horayot/English/Sefaria Community Translation",
         @"Mishnah/Seder Nezikin/Mishnah Horayot/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Nezikin/Mishnah Makkot/English/Open Mishna",
         @"Mishnah/Seder Nezikin/Mishnah Makkot/English/Sefaria Community Translation",
         @"Mishnah/Seder Nezikin/Mishnah Makkot/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Nezikin/Mishnah Sanhedrin/English/Open Mishna",
         @"Mishnah/Seder Nezikin/Mishnah Sanhedrin/English/Sefaria Community Translation",
         @"Mishnah/Seder Nezikin/Mishnah Sanhedrin/English/Soncino",
         @"Mishnah/Seder Nezikin/Mishnah Sanhedrin/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Nezikin/Mishnah Shevuot/English/Open Mishna",
         @"Mishnah/Seder Nezikin/Mishnah Shevuot/English/Sefaria Community Translation",
         @"Mishnah/Seder Nezikin/Mishnah Shevuot/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Nezikin/Pirkei Avot/English/Open Mishna",
         @"Mishnah/Seder Nezikin/Pirkei Avot/English/Sefaria Community Translation",
         @"Mishnah/Seder Nezikin/Pirkei Avot/English/The Saying of the Jewish Fathers Gorfinkle 1913",
         @"Mishnah/Seder Nezikin/Pirkei Avot/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Tahorot/Mishnah Kelim/English/Sefaria Community Translation",
         @"Mishnah/Seder Tahorot/Mishnah Kelim/English/Sefaria Translation",
         @"Mishnah/Seder Tahorot/Mishnah Kelim/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Tahorot/Mishnah Makhshirin/English/Sefaria Community Translation",
         @"Mishnah/Seder Tahorot/Mishnah Makhshirin/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Tahorot/Mishnah Mikvaot/English/Sefaria Community Translation",
         @"Mishnah/Seder Tahorot/Mishnah Mikvaot/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Tahorot/Mishnah Negaim/English/Sefaria Community Translation",
         @"Mishnah/Seder Tahorot/Mishnah Negaim/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Tahorot/Mishnah Niddah/English/Sefaria Community Translation",
         @"Mishnah/Seder Tahorot/Mishnah Niddah/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Tahorot/Mishnah Oholot/English/Sefaria Community Translation",
         @"Mishnah/Seder Tahorot/Mishnah Oholot/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Tahorot/Mishnah Oktzin/English/Open Mishna",
         @"Mishnah/Seder Tahorot/Mishnah Oktzin/English/Sefaria Community Translation",
         @"Mishnah/Seder Tahorot/Mishnah Oktzin/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Tahorot/Mishnah Parah/English/Open Mishna",
         @"Mishnah/Seder Tahorot/Mishnah Parah/English/Sefaria Community Translation",
         @"Mishnah/Seder Tahorot/Mishnah Parah/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Tahorot/Mishnah Tahorot/English/Sefaria Community Translation",
         @"Mishnah/Seder Tahorot/Mishnah Tahorot/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Tahorot/Mishnah Tevul Yom/English/Sefaria Community Translation",
         @"Mishnah/Seder Tahorot/Mishnah Tevul Yom/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Tahorot/Mishnah Yadayim/English/Eighteen Treatises from the Mishna",
         @"Mishnah/Seder Tahorot/Mishnah Yadayim/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Tahorot/Mishnah Zavim/English/Sefaria Community Translation",
         @"Mishnah/Seder Tahorot/Mishnah Zavim/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Zeraim/Mishnah Berakhot/English/Eighteen Treatises from the Mishna",
         @"Mishnah/Seder Zeraim/Mishnah Berakhot/English/Open Mishna",
         @"Mishnah/Seder Zeraim/Mishnah Berakhot/English/Sefaria Community Translation",
         @"Mishnah/Seder Zeraim/Mishnah Berakhot/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Zeraim/Mishnah Bikkurim/English/Sefaria Community Translation",
         @"Mishnah/Seder Zeraim/Mishnah Bikkurim/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Zeraim/Mishnah Challah/English/Sefaria Community Translation",
         @"Mishnah/Seder Zeraim/Mishnah Challah/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Zeraim/Mishnah Demai/English/Open Mishna",
         @"Mishnah/Seder Zeraim/Mishnah Demai/English/Sefaria Community Translation",
         @"Mishnah/Seder Zeraim/Mishnah Demai/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Zeraim/Mishnah Kilayim/English/Eighteen Treatises from the Mishna",
         @"Mishnah/Seder Zeraim/Mishnah Kilayim/English/Sefaria Community Translation",
         @"Mishnah/Seder Zeraim/Mishnah Kilayim/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Zeraim/Mishnah Maaser Sheni/English/Sefaria Community Translation",
         @"Mishnah/Seder Zeraim/Mishnah Maaser Sheni/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Zeraim/Mishnah Maasrot/English/Sefaria Community Translation",
         @"Mishnah/Seder Zeraim/Mishnah Maasrot/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Zeraim/Mishnah Orlah/English/Sefaria Community Translation",
         @"Mishnah/Seder Zeraim/Mishnah Orlah/English/Wikisource Mishna",
         @"Mishnah/Seder Zeraim/Mishnah Orlah/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Zeraim/Mishnah Peah/English/Open Mishna",
         @"Mishnah/Seder Zeraim/Mishnah Peah/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Zeraim/Mishnah Sheviit/English/Sefaria Community Translation",
         @"Mishnah/Seder Zeraim/Mishnah Sheviit/Hebrew/Mishna Sheviit  Chapter 7",
         @"Mishnah/Seder Zeraim/Mishnah Sheviit/Hebrew/Mishna Sheviit Chapter 8",
         @"Mishnah/Seder Zeraim/Mishnah Sheviit/Hebrew/Wikisource Mishna",
         @"Mishnah/Seder Zeraim/Mishnah Terumot/English/Mishna Yomit",
         @"Mishnah/Seder Zeraim/Mishnah Terumot/English/Sefaria Community Translation",
         @"Mishnah/Seder Zeraim/Mishnah Terumot/Hebrew/Wikisource Mishna",
         
         @"Musar/Messilat Yesharim/English/Messillat Yesharim",
         @"Musar/Messilat Yesharim/Hebrew/Hakdama",
         @"Musar/Messilat Yesharim/Hebrew/Perek 1",
         @"Musar/Messilat Yesharim/Hebrew/Perek 10",
         @"Musar/Messilat Yesharim/Hebrew/Perek 11",
         @"Musar/Messilat Yesharim/Hebrew/Perek 12",
         @"Musar/Messilat Yesharim/Hebrew/Perek 13",
         @"Musar/Messilat Yesharim/Hebrew/Perek 14",
         @"Musar/Messilat Yesharim/Hebrew/Perek 15",
         @"Musar/Messilat Yesharim/Hebrew/Perek 16",
         @"Musar/Messilat Yesharim/Hebrew/Perek 17",
         @"Musar/Messilat Yesharim/Hebrew/Perek 18",
         @"Musar/Messilat Yesharim/Hebrew/Perek 19",
         @"Musar/Messilat Yesharim/Hebrew/Perek 2",
         @"Musar/Messilat Yesharim/Hebrew/Perek 20",
         @"Musar/Messilat Yesharim/Hebrew/Perek 21",
         @"Musar/Messilat Yesharim/Hebrew/Perek 22",
         @"Musar/Messilat Yesharim/Hebrew/Perek 23",
         @"Musar/Messilat Yesharim/Hebrew/Perek 24",
         @"Musar/Messilat Yesharim/Hebrew/Perek 26",
         @"Musar/Messilat Yesharim/Hebrew/Perek 3",
         @"Musar/Messilat Yesharim/Hebrew/Perek 4",
         @"Musar/Messilat Yesharim/Hebrew/Perek 5",
         @"Musar/Messilat Yesharim/Hebrew/Perek 6",
         @"Musar/Messilat Yesharim/Hebrew/Perek 7",
         @"Musar/Messilat Yesharim/Hebrew/Perek 8",
         @"Musar/Messilat Yesharim/Hebrew/Perek 9",
         @"Musar/Messilat Yesharim/Hebrew/Perek25",
         
         @"Other/Dictionary/Sefer haArouch/Hebrew/ספר הערוך לריב נתן בן יחיאל מרומי אות כ' ערך כפש",
         @"Other/Early Jewish Thought/Sefer Hasidim/English/Sefaria Community Translation",
         @"Other/Megillat Taanit/Hebrew/daat.co.il",
         @"Other/Piyutim/Shir HaKavod/English/1",
         @"Other/Piyutim/Shir HaKavod/English/Sefaria Community Translation",
         @"Other/Targum/Aramaic Targum to Song of Songs/English/English Translation by Jay Treat",
         @"Other/Targum/Aramaic Targum to Song of Songs/English/Jay Treat's English Translation",
         @"Other/Targum/Aramaic Targum to Song of Songs/English/Sefaria Community Translation",
         @"Other/Targum/Onkelos Deuteronomy/Hebrew/Onkelos Deuteronomy",
         @"Other/Targum/Onkelos Exodus/Hebrew/Onkelos Exodus",
         @"Other/Targum/Onkelos Genesis/Hebrew/Onkelos Genesis",
         @"Other/Targum/Onkelos Leviticus/Hebrew/Onkelos Leviticus",
         @"Other/Targum/Onkelos Numbers/English/Sefaria Community Translation",
         @"Other/Targum/Onkelos Numbers/Hebrew/Onkelos Numbers",
         @"Other/Targum/Targum Jonathan on Deuteronomy/Hebrew/Targum Jonathan on Deuteronomy",
         @"Other/Targum/Targum Jonathan on Exodus/Hebrew/Targum Jonathan on Exodus",
         @"Other/Targum/Targum Jonathan on Genesis/Hebrew/Targum Jonathan on Genesis",
         @"Other/Targum/Targum Jonathan on Leviticus/Hebrew/Targum Jonathan on Leviticus",
         @"Other/Targum/Targum Jonathan on Numbers/Hebrew/Targum Jonathan on Numbers",
         
         @"Philosophy/Chovot Halevavot/English/Sefaria Community Translation",
         @"Philosophy/Chovot Halevavot/English/Shaar HaYichud",
         @"Philosophy/Eight Chapters/Hebrew/Dr. Asher Ben Yisrael",
         @"Philosophy/Ein Ayah/Hebrew/Rav Kook Digitized Texts",
         @"Philosophy/For the Perplexed of the Generation/English/Harav Kook- leNevuchai Hazeman",
         @"Philosophy/For the Perplexed of the Generation/English/Sefaria Community Translation",
         @"Philosophy/For the Perplexed of the Generation/Hebrew/ Harav Kook- leNevuchai Hazeman",
         @"Philosophy/For the Perplexed of the Generation/Hebrew/ Harav Kook- leNevuchai Hazeman",
         @"Philosophy/For the Perplexed of the Generation/Hebrew/Harav Kook- leNevuchai Hazeman",
         @"Philosophy/Guide for the Perplexed/English/Friedlander Guide for the Perplexed on Wikisource",
         @"Philosophy/Guide for the Perplexed/Hebrew/OnYourWay",
         @"Philosophy/Kad HaKemach/English/Sefaria Community Translation",
         @"Philosophy/Netivot Olam/English/Sefaria Community Translation",
         @"Philosophy/Netivot Olam/Hebrew/Wikisource Netivot Olam",
         @"Philosophy/Orot HaKodesh/Hebrew/Orot HaKodesh -- Wikitext",
         @"Philosophy/Sefer Kuzari/English/Sefaria Community Translation",
         @"Philosophy/Sefer Kuzari/English/Sefer HaKuzari",
         @"Philosophy/Sefer Kuzari/Hebrew/First Essay",
         @"Philosophy/Sefer Kuzari/Hebrew/Part 2",
         @"Philosophy/Sefer Kuzari/Hebrew/Part 3",
         @"Philosophy/Sefer Kuzari/Hebrew/Part 4",
         @"Philosophy/Sefer Kuzari/Hebrew/Part 5",
         @"Philosophy/Shmonah Kevatzim/Hebrew/Rav Kook public files",
         @"Philosophy/Shmonah Kevatzim/Hebrew/Shmonah Kevatzim -- Wikisource",
         
         @"Talmud/Bavli/Seder Kodashim/Arakhin/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Kodashim/Bekhorot/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Kodashim/Chullin/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Kodashim/Chullin/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Kodashim/Keritot/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Kodashim/Meilah/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Kodashim/Menachot/Hebrew/Bavli Menachot 43b",
         @"Talmud/Bavli/Seder Kodashim/Menachot/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Kodashim/Tamid/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Kodashim/Temurah/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Kodashim/Zevachim/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Moed/Beitzah/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Moed/Beitzah/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Moed/Chagigah/English/English",
         @"Talmud/Bavli/Seder Moed/Chagigah/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Moed/Chagigah/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Moed/Eruvin/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Moed/Eruvin/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Moed/Megillah/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Moed/Megillah/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Moed/Moed Katan/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Moed/Pesachim/English/En Jacob Rabbi S.H. Glick",
         @"Talmud/Bavli/Seder Moed/Pesachim/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Moed/Pesachim/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Moed/Rosh Hashanah/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Moed/Rosh Hashanah/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Moed/Shabbat/English/English",
         @"Talmud/Bavli/Seder Moed/Shabbat/English/Jewish Virtual Library",
         @"Talmud/Bavli/Seder Moed/Shabbat/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Moed/Shabbat/English/Shabbat 88b",
         @"Talmud/Bavli/Seder Moed/Shabbat/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Moed/Sukkah/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Moed/Sukkah/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Moed/Taanit/English/Sara Daniel's translation",
         @"Talmud/Bavli/Seder Moed/Taanit/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Moed/Taanit/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Moed/Yoma/English/En Jacob",
         @"Talmud/Bavli/Seder Moed/Yoma/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Moed/Yoma/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Moed/Yoma/Hebrew/Yoma 80b",
         @"Talmud/Bavli/Seder Nashim/Gittin/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Nashim/Gittin/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Nashim/Ketubot/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Nashim/Ketubot/English/Soncino English Translation",
         @"Talmud/Bavli/Seder Nashim/Ketubot/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Nashim/Kiddushin/English/Kiddushin 30a 4",
         @"Talmud/Bavli/Seder Nashim/Kiddushin/English/Kiddushin 38a",
         @"Talmud/Bavli/Seder Nashim/Kiddushin/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Nashim/Kiddushin/English/Soncino Translation",
         @"Talmud/Bavli/Seder Nashim/Kiddushin/English/Translation of Kiddushin 22b1",
         @"Talmud/Bavli/Seder Nashim/Kiddushin/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Nashim/Nazir/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Nashim/Nedarim/English/Soncino English Translation",
         @"Talmud/Bavli/Seder Nashim/Nedarim/English/Soncino",
         @"Talmud/Bavli/Seder Nashim/Nedarim/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Nashim/Sotah/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Nashim/Sotah/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Nashim/Yevamot/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Nashim/Yevamot/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Nezikin/Avodah Zarah/English/Avodah Zara",
         @"Talmud/Bavli/Seder Nezikin/Avodah Zarah/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Nezikin/Avodah Zarah/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Nezikin/Bava Batra/English/section on Bnot Zelophchad",
         @"Talmud/Bavli/Seder Nezikin/Bava Batra/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Nezikin/Bava Batra/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Nezikin/Bava Kamma/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Nezikin/Bava Kamma/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Nezikin/Bava Metzia/English/Found online",
         @"Talmud/Bavli/Seder Nezikin/Bava Metzia/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Nezikin/Bava Metzia/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Nezikin/Horayot/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Nezikin/Horayot/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Nezikin/Makkot/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Nezikin/Makkot/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Nezikin/Sanhedrin/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Nezikin/Sanhedrin/English/Soncino Babylonian Talmud",
         @"Talmud/Bavli/Seder Nezikin/Sanhedrin/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Nezikin/Shevuot/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Tahorot/Niddah/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Zeraim/Berakhot/English/Come & Hear",
         @"Talmud/Bavli/Seder Zeraim/Berakhot/English/Sefaria Community Translation",
         @"Talmud/Bavli/Seder Zeraim/Berakhot/English/Soncino",
         @"Talmud/Bavli/Seder Zeraim/Berakhot/English/Wikisource Talmud",
         @"Talmud/Bavli/Seder Zeraim/Berakhot/Hebrew/Wikisource Talmud Bavli",
         @"Talmud/Bavli/Seder Zeraim/Berakhot/Hebrew/בבלי_ברכות_פרק_א_מנוקד_ומעוצב",
         @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Beitzah/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Chagigah/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Eiruvin/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Megillah/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Moed Kattan/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Pesachim/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Rosh Hashanah/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Shabbat/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Shekalim/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Sukkah/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Ta'anit/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Yoma/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Nashim/Jerusalem Talmud Gittin/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Nashim/Jerusalem Talmud Ketubot/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Nashim/Jerusalem Talmud Kiddushin/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Nashim/Jerusalem Talmud Nazir/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Nashim/Jerusalem Talmud Nedarim/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Nashim/Jerusalem Talmud Sotah/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Nashim/Jerusalem Talmud Yevamot/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Nezikin/Jerusalem Talmud Avodah Zarah/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Nezikin/Jerusalem Talmud Bava Batra/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Nezikin/Jerusalem Talmud Bava Kamma/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Nezikin/Jerusalem Talmud Bava Metsia/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Nezikin/Jerusalem Talmud Horayot/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Nezikin/Jerusalem Talmud Makkot/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Nezikin/Jerusalem Talmud Sanhedrin/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Nezikin/Jerusalem Talmud Shevuot/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Tahorot/Jerusalem Talmud Niddah/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Berakhot/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Bikkurim/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Demai/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Hallah/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Kilayim/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Ma'aser Sheni/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Ma'asrot/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Orlah/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Peah/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Shevi'it/Hebrew/Mechon Mamre Talmud Yerushalmi",
         @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Terumot/Hebrew/Mechon Mamre Talmud Yerushalmi",
         
         @"Tanach/Prophets/Amos/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Prophets/Amos/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Prophets/Amos/Hebrew/Wikisource Tanach",
         @"Tanach/Prophets/Ezekiel/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Prophets/Ezekiel/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Prophets/Ezekiel/Hebrew/Wikisource Tanach",
         @"Tanach/Prophets/Habakkuk/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Prophets/Habakkuk/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Prophets/Habakkuk/Hebrew/Wikisource Tanach",
         @"Tanach/Prophets/Haggai/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Prophets/Haggai/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Prophets/Haggai/Hebrew/Wikisource Tanach",
         @"Tanach/Prophets/Hosea/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Prophets/Hosea/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Prophets/Hosea/Hebrew/Wikisource Tanach",
         @"Tanach/Prophets/I Kings/English/Sefaria Community Translation",
         @"Tanach/Prophets/I Kings/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Prophets/I Kings/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Prophets/I Kings/Hebrew/Wikisource Tanach",
         @"Tanach/Prophets/I Samuel/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Prophets/I Samuel/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Prophets/I Samuel/Hebrew/Wikisource Tanach",
         @"Tanach/Prophets/II Kings/English/Kings II",
         @"Tanach/Prophets/II Kings/English/Sefaria Community Translation",
         @"Tanach/Prophets/II Kings/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Prophets/II Kings/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Prophets/II Kings/Hebrew/Wikisource Tanach",
         @"Tanach/Prophets/II Samuel/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Prophets/II Samuel/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Prophets/II Samuel/Hebrew/Wikisource Tanach",
         @"Tanach/Prophets/Isaiah/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Prophets/Isaiah/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Prophets/Isaiah/Hebrew/Wikisource Tanach",
         @"Tanach/Prophets/Jeremiah/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Prophets/Jeremiah/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Prophets/Jeremiah/Hebrew/Wikisource Tanach",
         @"Tanach/Prophets/Joel/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Prophets/Joel/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Prophets/Joel/Hebrew/Wikisource Tanach",
         @"Tanach/Prophets/Jonah/English/Modernized Tanakh - Based on JPS 1917, Edited by Adam Cohn",
         @"Tanach/Prophets/Jonah/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Prophets/Jonah/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Prophets/Jonah/Hebrew/Wikisource Tanach",
         @"Tanach/Prophets/Joshua/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Prophets/Joshua/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Prophets/Joshua/Hebrew/Wikisource Tanach",
         @"Tanach/Prophets/Judges/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Prophets/Judges/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Prophets/Judges/Hebrew/Wikisource Tanach",
         @"Tanach/Prophets/Malachi/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Prophets/Malachi/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Prophets/Malachi/Hebrew/Wikisource Tanach",
         @"Tanach/Prophets/Micah/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Prophets/Micah/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Prophets/Micah/Hebrew/Wikisource Tanach",
         @"Tanach/Prophets/Nahum/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Prophets/Nahum/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Prophets/Nahum/Hebrew/Wikisource Tanach",
         @"Tanach/Prophets/Obadiah/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Prophets/Obadiah/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Prophets/Obadiah/Hebrew/Wikisource Tanach",
         @"Tanach/Prophets/Zechariah/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Prophets/Zechariah/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Prophets/Zechariah/Hebrew/Wikisource Tanach",
         @"Tanach/Prophets/Zephaniah/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Prophets/Zephaniah/Hebrew/Wikisource Tanach with Trop",
         @"Tanach/Prophets/Zephaniah/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Prophets/Zephaniah/Hebrew/Wikisource Tanach",
         @"Tanach/Torah/Deuteronomy/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Torah/Deuteronomy/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Torah/Deuteronomy/Hebrew/Wikisource Tanach",
         @"Tanach/Torah/Exodus/English/JPS 1985",
         @"Tanach/Torah/Exodus/English/Sefaria Community Translation",
         @"Tanach/Torah/Exodus/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Torah/Exodus/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Torah/Exodus/Hebrew/Wikisource Tanach",
         @"Tanach/Torah/Genesis/English/Jewish English Torah",
         @"Tanach/Torah/Genesis/English/Modernized Tanakh - Based on JPS 1917, Edited by Adam Cohn",
         @"Tanach/Torah/Genesis/English/Sefaria Community Translation",
         @"Tanach/Torah/Genesis/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Torah/Genesis/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Torah/Genesis/Hebrew/Wikisource Tanach",
         @"Tanach/Torah/Leviticus/English/Easy to Read",
         @"Tanach/Torah/Leviticus/English/Sefaria Community Translation",
         @"Tanach/Torah/Leviticus/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Torah/Leviticus/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Torah/Leviticus/Hebrew/Wikisource Tanach",
         @"Tanach/Torah/Numbers/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Torah/Numbers/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Torah/Numbers/Hebrew/Wikisource Tanach",
         @"Tanach/Writings/Daniel/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Writings/Daniel/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Writings/Daniel/Hebrew/Wikisource Tanach",
         @"Tanach/Writings/Ecclesiastes/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Writings/Ecclesiastes/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Writings/Ecclesiastes/Hebrew/Wikisource Tanach",
         @"Tanach/Writings/Esther/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Writings/Esther/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Writings/Esther/Hebrew/Wikisource Tanach",
         @"Tanach/Writings/Ezra/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Writings/Ezra/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Writings/Ezra/Hebrew/Wikisource Tanach",
         @"Tanach/Writings/I Chronicles/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Writings/I Chronicles/Hebrew/Hebrew Text from Chabad.org",
         @"Tanach/Writings/I Chronicles/Hebrew/Wikisource Tanach with Trop",
         @"Tanach/Writings/I Chronicles/Hebrew/Wikisource Tanach",
         @"Tanach/Writings/I Chronicles/Hebrew/Wikisource Tanach1",
         @"Tanach/Writings/II Chronicles/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Writings/II Chronicles/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Writings/II Chronicles/Hebrew/Wikisource Tanach",
         @"Tanach/Writings/Job/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Writings/Job/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Writings/Job/Hebrew/Wikisource Tanach",
         @"Tanach/Writings/Lamentations/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Writings/Lamentations/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Writings/Lamentations/Hebrew/Wikisource Tanach",
         @"Tanach/Writings/Nehemiah/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Writings/Nehemiah/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Writings/Nehemiah/Hebrew/Wikisource Tanach",
         @"Tanach/Writings/Proverbs/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Writings/Proverbs/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Writings/Proverbs/Hebrew/Wikisource Tanach",
         @"Tanach/Writings/Psalms/English/Sefaria Community Translation",
         @"Tanach/Writings/Psalms/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Writings/Psalms/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Writings/Psalms/Hebrew/Wikisource Tanach",
         @"Tanach/Writings/Ruth/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Writings/Ruth/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Writings/Ruth/Hebrew/Wikisource Tanach",
         @"Tanach/Writings/Song of Songs/English/The Holy Scriptures A New Translation JPS 1917",
         @"Tanach/Writings/Song of Songs/Hebrew/Wikisource Tanach with Trope",
         @"Tanach/Writings/Song of Songs/Hebrew/Wikisource Tanach",
         
         @"Tosefta/Seder Kodashim/Tosefta Arakhin/Hebrew/Tosefta Arakhin - Machon Mamre",
         @"Tosefta/Seder Kodashim/Tosefta Bekhorot/Hebrew/Tosefta Bekhorot - Machon Mamre",
         @"Tosefta/Seder Kodashim/Tosefta Chullin/Hebrew/Tosefta Chullin - Machon Mamre",
         @"Tosefta/Seder Kodashim/Tosefta Keritot/Hebrew/Tosefta Keritot - Machon Mamre",
         @"Tosefta/Seder Kodashim/Tosefta Meilah/Hebrew/Tosefta Meilah",
         @"Tosefta/Seder Kodashim/Tosefta Menahot/Hebrew/Tosefta Menahot - Machon Mamre",
         @"Tosefta/Seder Kodashim/Tosefta Temurah/Hebrew/Tosefta Temurah - Machon Mamre",
         @"Tosefta/Seder Kodashim/Tosefta Zevahim/Hebrew/Tosefta Zevachim - Machon Mamre",
         @"Tosefta/Seder Moed/Tosefta Beitsah/English/Sefaria Community Translation",
         @"Tosefta/Seder Moed/Tosefta Beitsah/Hebrew/Tosefta - Machon Mamre",
         @"Tosefta/Seder Moed/Tosefta Chagigah/Hebrew/Tosefta Chagigah - Machon Mamre",
         @"Tosefta/Seder Moed/Tosefta Eiruvin/Hebrew/Tosefta Eruvin",
         @"Tosefta/Seder Moed/Tosefta Megillah/Hebrew/Tosefta Megillah - Machon Mamre",
         @"Tosefta/Seder Moed/Tosefta Megillah/Hebrew/Tosefta",
         @"Tosefta/Seder Moed/Tosefta Moed Kattan/Hebrew/Tosefta Moed Katan - Machon Mamre",
         @"Tosefta/Seder Moed/Tosefta Pesachim/Hebrew/Tosefta Pesachim",
         @"Tosefta/Seder Moed/Tosefta Rosh HaShanah/Hebrew/Tosefta Rosh Hashanah  -- Machon Mamre",
         @"Tosefta/Seder Moed/Tosefta Shabbat/English/Sefaria Community Translation",
         @"Tosefta/Seder Moed/Tosefta Shabbat/Hebrew/Tosefta Shabbat",
         @"Tosefta/Seder Moed/Tosefta Shekalim/Hebrew/Tosefta Shekalim",
         @"Tosefta/Seder Moed/Tosefta Sukkah/English/Sefaria Community Translation",
         @"Tosefta/Seder Moed/Tosefta Sukkah/Hebrew/Tosefta Sukkah",
         @"Tosefta/Seder Moed/Tosefta Ta'anit/Hebrew/Tosefta Ta'anit -- Machon Mamre",
         @"Tosefta/Seder Moed/Tosefta Yoma/Hebrew/Tosefta Yoma",
         @"Tosefta/Seder Nashim/Tosefta Gittin/Hebrew/Tosefta Gittin - Machon Mamre",
         @"Tosefta/Seder Nashim/Tosefta Ketubot/Hebrew/Tosefta Ketuvot -- Machon Mamre",
         @"Tosefta/Seder Nashim/Tosefta Kiddushin/Hebrew/Tosefta Kidushin - Machon Mamre",
         @"Tosefta/Seder Nashim/Tosefta Nazir/Hebrew/Tosefta Nazir - Machon Mamre",
         @"Tosefta/Seder Nashim/Tosefta Nedarim/Hebrew/Tosefta Nedarim - Machon Mamre",
         @"Tosefta/Seder Nashim/Tosefta Sotah/Hebrew/Tosefta Sota - Machon Mamre",
         @"Tosefta/Seder Nashim/Tosefta Yevamot/Hebrew/Tosefta Yevamot -- Machon Mamre",
         @"Tosefta/Seder Nezikin/Tosefta Avodah Zarah/Hebrew/Tosefta Avodah Zarah - Machon Mamre",
         @"Tosefta/Seder Nezikin/Tosefta Bava Batra/Hebrew/Tosefta Bava Batra - Machon Mamre",
         @"Tosefta/Seder Nezikin/Tosefta Bava Kamma/Hebrew/Tosefta Bava Kamma - Machon Mamre",
         @"Tosefta/Seder Nezikin/Tosefta Bava Metzia/English/Sefaria Community Translation",
         @"Tosefta/Seder Nezikin/Tosefta Bava Metzia/Hebrew/Tosefta Bava Metziah - Machon Mamre",
         @"Tosefta/Seder Nezikin/Tosefta Eduyot/Hebrew/Tosefta Eduyot - Machon Mamre",
         @"Tosefta/Seder Nezikin/Tosefta Horayot/Hebrew/Tosefta Horayot - Machon Mamre",
         @"Tosefta/Seder Nezikin/Tosefta Makkot/Hebrew/Tosefta Makkot - Machon Mamre",
         @"Tosefta/Seder Nezikin/Tosefta Sanhedrin/Hebrew/Tosefta Sanhedrin - Machon Mamre",
         @"Tosefta/Seder Nezikin/Tosefta Shevuot/Hebrew/Tosefta Shevuot - Machon Mamre",
         @"Tosefta/Seder Toharot/Tosefta Keilim Batra/Hebrew/Tosefta Keilim Batra - Machon Mamre",
         @"Tosefta/Seder Toharot/Tosefta Keilim Kamma/Hebrew/Tosefta Keilim Kamma - Machon Mamre",
         @"Tosefta/Seder Toharot/Tosefta Keilim Metsia/English/Sefaria Community Translation",
         @"Tosefta/Seder Toharot/Tosefta Keilim Metsia/Hebrew/Tosefta Keilim Metsia - Machon Mamre",
         @"Tosefta/Seder Toharot/Tosefta Makhshirin/Hebrew/Tosefta Makhshirin - Machon Mamre",
         @"Tosefta/Seder Toharot/Tosefta Mikvaot/Hebrew/Tosefta Mikvaot - Machon Mamre",
         @"Tosefta/Seder Toharot/Tosefta Negaim/Hebrew/Tosefta Negaim - Machon Mamre",
         @"Tosefta/Seder Toharot/Tosefta Niddah/Hebrew/Tosefta Niddah - Machon Mamre",
         @"Tosefta/Seder Toharot/Tosefta Ohalot/Hebrew/Tosefta Ohalot - Machon Mamre",
         @"Tosefta/Seder Toharot/Tosefta Parah/Hebrew/Tosefta Parah - Machon Mamre",
         @"Tosefta/Seder Toharot/Tosefta Tevul Yom/Hebrew/Tosefta Tevul Yom - Machon Mamre",
         @"Tosefta/Seder Toharot/Tosefta Tohorot/Hebrew/Tosefta Tohorot - Machon Mamre",
         @"Tosefta/Seder Toharot/Tosefta Uktsin/Hebrew/Tosefta Uktsin - Machon Mamre",
         @"Tosefta/Seder Toharot/Tosefta Yadayim/Hebrew/Tosefta Yadayim -  Machon Mamre",
         @"Tosefta/Seder Toharot/Tosefta Zavim/Hebrew/Tosefta Zavim - Machon Mamre",
         @"Tosefta/Seder Zeraim/Tosefta Berakhot/English/Sefaria Community Translation",
         @"Tosefta/Seder Zeraim/Tosefta Berakhot/English/Tosefta Online",
         @"Tosefta/Seder Zeraim/Tosefta Berakhot/Hebrew/Tosefta B'rachot 1",
         @"Tosefta/Seder Zeraim/Tosefta Berakhot/Hebrew/Tosefta B'rachot",
         @"Tosefta/Seder Zeraim/Tosefta Bikkurim/Hebrew/Tosefta Bikkurim",
         @"Tosefta/Seder Zeraim/Tosefta Challah/Hebrew/Tosefta Challah",
         @"Tosefta/Seder Zeraim/Tosefta Demai/Hebrew/Tosefta Dem'ai",
         @"Tosefta/Seder Zeraim/Tosefta Demai/Hebrew/Tosefta Dem'ai",
         @"Tosefta/Seder Zeraim/Tosefta Kilaim/Hebrew/Tosefta  Kilayim",
         @"Tosefta/Seder Zeraim/Tosefta Kilaim/Hebrew/Tosefta Kilayim",
         @"Tosefta/Seder Zeraim/Tosefta Ma'aser Sheni/Hebrew/Tosefta Maaser Sheini",
         @"Tosefta/Seder Zeraim/Tosefta Ma'asrot/Hebrew/Tosefta Maasrot",
         @"Tosefta/Seder Zeraim/Tosefta Orlah/Hebrew/Tosefta Orlah",
         @"Tosefta/Seder Zeraim/Tosefta Peah/English/Sefaria Community Translation",
         @"Tosefta/Seder Zeraim/Tosefta Peah/English/The Tosefta Blog",
         @"Tosefta/Seder Zeraim/Tosefta Peah/Hebrew/Tosefta Pei'ah 3",
         @"Tosefta/Seder Zeraim/Tosefta Peah/Hebrew/Tosefta Pei'ah 4",
         @"Tosefta/Seder Zeraim/Tosefta Peah/Hebrew/Tosefta Pei'ah",
         @"Tosefta/Seder Zeraim/Tosefta Shevi'it/Hebrew/ Tosefta Shvi'it",
         @"Tosefta/Seder Zeraim/Tosefta Shevi'it/Hebrew/Tosefta Shvi'it 8",
         @"Tosefta/Seder Zeraim/Tosefta Shevi'it/Hebrew/Tosefta Shvi'it",
         @"Tosefta/Seder Zeraim/Tosefta Terumot/Hebrew/ Tosefta Terumot",
         @"Tosefta/Seder Zeraim/Tosefta Terumot/Hebrew/Tosefta Terumot"
        ];
}



@end
