//
//  BookListDataModel.m
//  Sefaria
//
//  Created by MGM on 7/14/14.
//  Copyright (c) 2014 Test. All rights reserved.
//

#import "BookListDataModel.h"

@implementation BookListDataModel

@synthesize theCompleteDictionary=_theCompleteDictionary,theCategoryList=_theCategoryList,theCompleteTextArray=_theCompleteTextArray;

#define DK 2
#define LOG if(DK == 1)

#define ROOT_PATH @"TextData/"

+ (BookListDataModel*) myNewDataLoader: (NSString*) filePathStringFromArray
{
    BookListDataModel* myTextDataModel = [[BookListDataModel alloc]init];
    
    NSString* fullString = [NSString stringWithFormat:@"%@%@",ROOT_PATH,filePathStringFromArray];
    
    NSString *filePath = [[NSBundle mainBundle] pathForResource: fullString ofType:@"json"];
    NSData *myData = [NSData dataWithContentsOfFile:filePath];
    
    
    if (myData == nil) {
        NSLog(@"-- Error - FS %@ --",fullString);
        NSLog(@"nil data");
    }
    
    //
    // NSJSONSerialization
    //
    NSError* error;
    myTextDataModel.theCompleteDictionary = [NSJSONSerialization JSONObjectWithData:myData
                                                                            options:kNilOptions
                                                                              error:&error];

    //
    // The Text
    //

    if ([myTextDataModel.theCompleteDictionary objectForKey:@"text"]) {
        myTextDataModel.theCompleteTextArray = [myTextDataModel.theCompleteDictionary objectForKey:@"text"];
        LOG NSLog(@"-- Full Text: %@ --",myTextDataModel.theCompleteTextArray);
    }
    else {
        LOG NSLog(@"Text Error");
        LOG NSLog(@"-- FullPath: %@ --",filePathStringFromArray);
        LOG NSLog(@"-- --");
    }
    
    //
    // languages
    //
    if ([myTextDataModel.theCompleteDictionary objectForKey:@"language"]) {
        myTextDataModel.theLanguage = [myTextDataModel.theCompleteDictionary objectForKey:@"language"];
        LOG NSLog(@"-- Language: %@ --",[myTextDataModel.theCompleteDictionary objectForKey:@"language"]);
    }
    else {
        LOG NSLog(@"Error for Language");
        LOG NSLog(@"-- FullPath: %@ --",filePathStringFromArray);
        LOG NSLog(@"-- --");
    }
    
    //
    // Titles
    //
    if ([myTextDataModel.theCompleteDictionary objectForKey:@"title"]) {
        myTextDataModel.theTitle = [myTextDataModel.theCompleteDictionary objectForKey:@"title"];
        LOG NSLog(@"-- Title: %@ --",[myTextDataModel.theCompleteDictionary objectForKey:@"title"]);
    }
    else {
        LOG NSLog(@"Error for English Title");
        LOG NSLog(@"-- FullPath: %@ --",filePathStringFromArray);
        LOG NSLog(@"-- --");
    }
    
    if ([myTextDataModel.theCompleteDictionary objectForKey:@"heTitle"]) {
        myTextDataModel.theHebrewTitle = [myTextDataModel.theCompleteDictionary objectForKey:@"heTitle"];
        LOG NSLog(@"-- Hebrew Title: %@ --",[myTextDataModel.theCompleteDictionary objectForKey:@"heTitle"]);
    }
    else {
        LOG NSLog(@"Error for Hebrew Title");
        LOG NSLog(@"-- FullPath: %@ --",filePathStringFromArray);
        LOG NSLog(@"-- --");
    }
    return myTextDataModel;
}

- (NSArray*) superTextList
{
    return @[
             @"Chasidut/Ba'al Shem Tov on the Torah/English/merged",
             @"Chasidut/Chiddushei HaRim Al HaTorah/English/merged",
             @"Chasidut/Chiddushei HaRim Al HaTorah/Hebrew/merged",
             @"Chasidut/Derekh Mitsvotekha/Hebrew/merged",
             @"Chasidut/Kedushat Levi/English/merged",
             @"Chasidut/Kedushat Levi/Hebrew/merged",
             @"Chasidut/Likutei Moharan/English/merged",
             @"Chasidut/Likutei Moharan/Hebrew/merged",
             @"Chasidut/Me'or Einayim/English/merged",
             @"Chasidut/Mekor Mayyim Hayyim/English/merged",
             @"Chasidut/Panim yafot/English/merged",
             @"Chasidut/Sefer Shel Benonim/English/merged",
             @"Chasidut/Sefer Shel Benonim/Hebrew/merged",
             @"Chasidut/Tanya/English/merged",
             @"Chasidut/Tanya/Hebrew/merged",
             @"Halakhah/Arbaah Turim/English/merged",
             @"Halakhah/Arbaah Turim/Hebrew/merged",
             @"Halakhah/Aruch HaShulchan/English/merged",
             @"Halakhah/Aruch HaShulchan/Hebrew/merged",
             @"Halakhah/Be'er Mayim Chaim/English/merged",
             @"Halakhah/Be'er Mayim Chaim/Hebrew/merged",
             @"Halakhah/Beit Yosef on Arba'ah Turim/Hebrew/merged",
             @"Halakhah/Ben Ish Hai/English/merged",
             @"Halakhah/Ben Ish Hai/Hebrew/merged",
             @"Halakhah/Chofetz Chaim/English/merged",
             @"Halakhah/Chofetz Chaim/Hebrew/merged",
             @"Halakhah/Issur V'Heter L'Rabbeinu Yerucham/Hebrew/merged",
             @"Halakhah/Kitzur Shulchan Aruch/English/merged",
             @"Halakhah/Kitzur Shulchan Aruch/Hebrew/merged",
             @"Halakhah/Kolbo/English/merged",
             @"Halakhah/Maaseh Rav/English/merged",
             @"Halakhah/Maaseh Rav/Hebrew/merged",
             @"Halakhah/Magen Avraham/English/merged",
             @"Halakhah/Magen Avraham/Hebrew/merged",
             @"Halakhah/Mishnah Berurah/English/merged",
             @"Halakhah/Mishnah Berurah/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Introduction/Mishneh Torah, Negative Mitzvot/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Introduction/Mishneh Torah, Overview of Mishneh Torah Contents/English/merged",
             @"Halakhah/Mishneh Torah/Introduction/Mishneh Torah, Overview of Mishneh Torah Contents/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Introduction/Mishneh Torah, Positive Mitzvot/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Introduction/Mishneh Torah, Transmission of the Oral Law/English/merged",
             @"Halakhah/Mishneh Torah/Introduction/Mishneh Torah, Transmission of the Oral Law/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, Blessings/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, Circumcision/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, Fringes/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, Prayer and the Priestly Blessing/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, Prayer and the Priestly Blessing/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, Reading the Shema/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, Reading the Shema/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, Tefillin, Mezuzah and the Torah Scroll/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Ahavah/Mishneh Torah, The Order of Prayer/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Avodah/Mishneh Torah, Admission into the Sanctuary/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Avodah/Mishneh Torah, Daily Offerings and Additional Offerings/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Avodah/Mishneh Torah, Sacrifices Rendered Unfit/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Avodah/Mishneh Torah, Sacrificial Procedure/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Avodah/Mishneh Torah, Service on the Day of Atonement/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Avodah/Mishneh Torah, The Chosen Temple/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Avodah/Mishneh Torah, Things Forbidden on the Alter/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Avodah/Mishneh Torah, Trespass/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Avodah/Mishneh Torah, Vessels of the Sanctuary and Those who Serve Therein/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Haflaah/Mishneh Torah, Appraisals and Devoted Property/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Haflaah/Mishneh Torah, Nazariteship/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Haflaah/Mishneh Torah, Oaths/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Haflaah/Mishneh Torah, Vows/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Kedushah/Mishneh Torah, Forbidden Foods/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Kedushah/Mishneh Torah, Forbidden Intercourse/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Kedushah/Mishneh Torah, Forbidden Intercourse/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Kedushah/Mishneh Torah, Ritual Slaughter/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Kedushah/Mishneh Torah, Ritual Slaughter/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Kinyan/Mishneh Torah, Agents and Partners/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Kinyan/Mishneh Torah, Neighbors/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Kinyan/Mishneh Torah, Ownerless Property and Gifts/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Kinyan/Mishneh Torah, Sales/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Kinyan/Mishneh Torah, Slaves/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Korbanot/Mishneh Torah, Festival Offering/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Korbanot/Mishneh Torah, Firstlings/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Korbanot/Mishneh Torah, Offerings for Those with Incomplete Atonement/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Korbanot/Mishneh Torah, Offerings for Unintentional Transgressions/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Korbanot/Mishneh Torah, Paschal Offering/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Korbanot/Mishneh Torah, Substitution/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Foreign Worship and Customs of the Nations/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Foreign Worship and Customs of the Nations/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Foundations of the Torah/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Foundations of the Torah/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Human Dispositions/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Human Dispositions/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Repentance/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Repentance/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Torah Study/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Madda/Mishneh Torah, Torah Study/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Mishpatim/Mishneh Torah, Borrowing and Deposit/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Mishpatim/Mishneh Torah, Creditor and Debtor/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Mishpatim/Mishneh Torah, Hiring/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Mishpatim/Mishneh Torah, Inheritances/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Mishpatim/Mishneh Torah, Plaintiff and Defendant/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Nashim/Mishneh Torah, Divorce/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Nashim/Mishneh Torah, Divorce/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Nashim/Mishneh Torah, Levirate Marriage and Release/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Nashim/Mishneh Torah, Marriage/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Nashim/Mishneh Torah, Marriage/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Nashim/Mishneh Torah, Virgin Maiden/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Nashim/Mishneh Torah, Woman Suspected of Infidelity/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Nashim/Mishneh Torah, Woman Suspected of Infidelity/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Nezikim/Mishneh Torah, Damages to Property/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Nezikim/Mishneh Torah, Murderer and the Preservation of Life/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Nezikim/Mishneh Torah, Murderer and the Preservation of Life/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Nezikim/Mishneh Torah, One Who Injures a Person or Property/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Nezikim/Mishneh Torah, Robbery and Lost Property/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Nezikim/Mishneh Torah, Theft/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Nezikim/Mishneh Torah, Theft/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Shoftim/Mishneh Torah, Kings and Wars/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Shoftim/Mishneh Torah, Kings and Wars/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Shoftim/Mishneh Torah, Mourning/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Shoftim/Mishneh Torah, Rebels/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Shoftim/Mishneh Torah, Testimony/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Shoftim/Mishneh Torah, Testimony/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Shoftim/Mishneh Torah, The Sanhedrin and the Penalties within their Jurisdiction/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Taharah/Mishneh Torah, Defilement by a Corpse/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Taharah/Mishneh Torah, Defilement by Leprosy/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Taharah/Mishneh Torah, Defilement by Leprosy/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Taharah/Mishneh Torah, Defilement of Foods/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Taharah/Mishneh Torah, Immersion Pools/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Taharah/Mishneh Torah, Other Sources of Defilement/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Taharah/Mishneh Torah, Red Heifer/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Taharah/Mishneh Torah, Those Who Defile Bed or Seat/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Taharah/Mishneh Torah, Vessels/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Eruvin/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Fasts/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Leavened and Unleavened Bread/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Leavened and Unleavened Bread/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Rest on a Holiday/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Rest on a Holiday/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Rest on the Tenth of Tishrei/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Sabbath/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Sanctification of the New Month/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Scroll of Esther and Hanukkah/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Scroll of Esther and Hanukkah/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Sheqel Dues/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Zemanim/Mishneh Torah, Shofar, Sukkah and Lulav/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Zeraim/Mishneh Torah, Diverse Species/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Zeraim/Mishneh Torah, First Fruits and other Gifts to Priests Outside the Sanctuary/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Zeraim/Mishneh Torah, First Fruits and other Gifts to Priests Outside the Sanctuary/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Zeraim/Mishneh Torah, Gifts to the Poor/English/merged",
             @"Halakhah/Mishneh Torah/Sefer Zeraim/Mishneh Torah, Gifts to the Poor/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Zeraim/Mishneh Torah, Heave Offerings/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Zeraim/Mishneh Torah, Sabbatical Year and the Jubilee/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Zeraim/Mishneh Torah, Second Tithes and Fourth Year's Fruit/Hebrew/merged",
             @"Halakhah/Mishneh Torah/Sefer Zeraim/Mishneh Torah, Tithes/Hebrew/merged",
             @"Halakhah/Sefer HaChinukh/English/merged",
             @"Halakhah/Sefer HaChinukh/Hebrew/merged",
             @"Halakhah/Sheiltot DeRav Achai/English/merged",
             @"Halakhah/Shulchan Aruch HaRav/English/merged",
             @"Halakhah/Shulchan Aruch HaRav/Hebrew/merged",
             @"Halakhah/Shulchan Arukh/Shulchan Arukh, Choshen Mishpat/English/merged",
             @"Halakhah/Shulchan Arukh/Shulchan Arukh, Choshen Mishpat/Hebrew/merged",
             @"Halakhah/Shulchan Arukh/Shulchan Arukh, Even HaEzer/English/merged",
             @"Halakhah/Shulchan Arukh/Shulchan Arukh, Even HaEzer/Hebrew/merged",
             @"Halakhah/Shulchan Arukh/Shulchan Arukh, Orach Chayyim/English/merged",
             @"Halakhah/Shulchan Arukh/Shulchan Arukh, Orach Chayyim/Hebrew/merged",
             @"Halakhah/Shulchan Arukh/Shulchan Arukh, Yoreh De'ah/English/merged",
             @"Halakhah/Shulchan Arukh/Shulchan Arukh, Yoreh De'ah/Hebrew/merged",
             @"Halakhah/Yalkut Yosef/English/merged",
             @"Kabbalah/Assarah Perakim L'Ramchal/Hebrew/merged",
             @"Kabbalah/Be'ur Eser S'firot/English/merged",
             @"Kabbalah/Be'ur Eser S'firot/Hebrew/merged",
             @"Kabbalah/Maggid Meisharim/Hebrew/merged",
             @"Kabbalah/Pardes Rimonim/Hebrew/merged",
             @"Kabbalah/Sefer Etz Chaim/Hebrew/merged",
             @"Kabbalah/Sefer HaBahir/Hebrew/merged",
             @"Kabbalah/Sefer HaQanah/Hebrew/merged",
             @"Kabbalah/Sefer Yetzirah/English/merged",
             @"Kabbalah/Sefer Yetzirah/Hebrew/merged",
             @"Kabbalah/Sharae Ora/English/merged",
             @"Kabbalah/Sharae Ora/Hebrew/merged",
             @"Kabbalah/Zohar/English/merged",
             @"Kabbalah/Zohar/Hebrew/merged",
             @"Liturgy/Ana BeKhoach/English/merged",
             @"Liturgy/Ana BeKhoach/Hebrew/merged",
             @"Liturgy/Hadran/English/merged",
             @"Liturgy/Hadran/Hebrew/merged",
             @"Liturgy/Kabbolos Shabbos/Hebrew/merged",
             @"Liturgy/Pesach Haggadah/English/merged",
             @"Liturgy/Pesach Haggadah/Hebrew/merged",
             @"Liturgy/Piyutim/Shir HaKavod/English/merged",
             @"Liturgy/Piyutim/Shir HaKavod/Hebrew/merged",
             @"Liturgy/Piyutim/Yedid Nefesh/English/merged",
             @"Liturgy/Piyutim/Yedid Nefesh/Hebrew/merged",
             @"Liturgy/Siddur/Shalom Alechem/English/merged",
             @"Liturgy/Siddur/Shalom Alechem/Hebrew/merged",
             @"Liturgy/Siddur/Weekday Siddur Ashkenaz/Hebrew/merged",
             @"Midrash/Bemidbar Rabbah/English/merged",
             @"Midrash/Bemidbar Rabbah/Hebrew/merged",
             @"Midrash/Bereishit Rabbah/English/merged",
             @"Midrash/Bereishit Rabbah/Hebrew/merged",
             @"Midrash/Devarim Rabbah/English/merged",
             @"Midrash/Devarim Rabbah/Hebrew/merged",
             @"Midrash/Eichah Rabbah/English/merged",
             @"Midrash/Eichah Rabbah/Hebrew/merged",
             @"Midrash/Ein Yaakov/English/merged",
             @"Midrash/Ein Yaakov/Hebrew/merged",
             @"Midrash/Esther Rabbah/English/merged",
             @"Midrash/Esther Rabbah/Hebrew/merged",
             @"Midrash/Kohelet Rabbah/English/merged",
             @"Midrash/Kohelet Rabbah/Hebrew/merged",
             @"Midrash/Legends of the Jews/English/merged",
             @"Midrash/Mekhilta/English/merged",
             @"Midrash/Mekhilta/Hebrew/merged",
             @"Midrash/Midrash B'not Zelophehad/English/merged",
             @"Midrash/Midrash on Proverbs/English/merged",
             @"Midrash/Midrash on Proverbs/Hebrew/merged",
             @"Midrash/Midrash Tanchuma/English/merged",
             @"Midrash/Midrash Tanchuma/Hebrew/merged",
             @"Midrash/Midrash Tehilim/English/merged",
             @"Midrash/Rut Rabba/English/merged",
             @"Midrash/Rut Rabba/Hebrew/merged",
             @"Midrash/Shemot Rabbah/English/merged",
             @"Midrash/Shemot Rabbah/Hebrew/merged",
             @"Midrash/Shir HaShirim Rabbah/Hebrew/merged",
             @"Midrash/Vayikra Rabbah/English/merged",
             @"Midrash/Vayikra Rabbah/Hebrew/merged",
             @"Midrash/Yalkut Shimoni/Hebrew/merged",
             
             @"Mishnah/Seder Kodashim/Mishnah Arakhin/English/merged",
             @"Mishnah/Seder Kodashim/Mishnah Arakhin/Hebrew/merged",
             @"Mishnah/Seder Kodashim/Mishnah Bekhorot/English/merged",
             @"Mishnah/Seder Kodashim/Mishnah Bekhorot/Hebrew/merged",
             @"Mishnah/Seder Kodashim/Mishnah Chullin/English/merged",
             @"Mishnah/Seder Kodashim/Mishnah Chullin/Hebrew/merged",
             @"Mishnah/Seder Kodashim/Mishnah Keritot/English/merged",
             @"Mishnah/Seder Kodashim/Mishnah Keritot/Hebrew/merged",
             @"Mishnah/Seder Kodashim/Mishnah Kinnim/English/merged",
             @"Mishnah/Seder Kodashim/Mishnah Kinnim/Hebrew/merged",
             @"Mishnah/Seder Kodashim/Mishnah Meilah/English/merged",
             @"Mishnah/Seder Kodashim/Mishnah Meilah/Hebrew/merged",
             @"Mishnah/Seder Kodashim/Mishnah Menachot/English/merged",
             @"Mishnah/Seder Kodashim/Mishnah Menachot/Hebrew/merged",
             @"Mishnah/Seder Kodashim/Mishnah Middot/English/merged",
             @"Mishnah/Seder Kodashim/Mishnah Middot/Hebrew/merged",
             @"Mishnah/Seder Kodashim/Mishnah Tamid/English/merged",
             @"Mishnah/Seder Kodashim/Mishnah Tamid/Hebrew/merged",
             @"Mishnah/Seder Kodashim/Mishnah Temurah/English/merged",
             @"Mishnah/Seder Kodashim/Mishnah Temurah/Hebrew/merged",
             @"Mishnah/Seder Kodashim/Mishnah Zevachim/English/merged",
             @"Mishnah/Seder Kodashim/Mishnah Zevachim/Hebrew/merged",
             @"Mishnah/Seder Moed/Mishnah Beitzah/English/merged",
             @"Mishnah/Seder Moed/Mishnah Beitzah/Hebrew/merged",
             @"Mishnah/Seder Moed/Mishnah Chagigah/English/merged",
             @"Mishnah/Seder Moed/Mishnah Chagigah/Hebrew/merged",
             @"Mishnah/Seder Moed/Mishnah Eruvin/English/merged",
             @"Mishnah/Seder Moed/Mishnah Eruvin/Hebrew/merged",
             @"Mishnah/Seder Moed/Mishnah Megillah/English/merged",
             @"Mishnah/Seder Moed/Mishnah Megillah/Hebrew/merged",
             @"Mishnah/Seder Moed/Mishnah Moed Katan/English/merged",
             @"Mishnah/Seder Moed/Mishnah Moed Katan/Hebrew/merged",
             @"Mishnah/Seder Moed/Mishnah Pesachim/English/merged",
             @"Mishnah/Seder Moed/Mishnah Pesachim/Hebrew/merged",
             @"Mishnah/Seder Moed/Mishnah Rosh Hashanah/English/merged",
             @"Mishnah/Seder Moed/Mishnah Rosh Hashanah/Hebrew/merged",
             @"Mishnah/Seder Moed/Mishnah Shabbat/English/merged",
             @"Mishnah/Seder Moed/Mishnah Shabbat/Hebrew/merged",
             @"Mishnah/Seder Moed/Mishnah Shekalim/English/merged",
             @"Mishnah/Seder Moed/Mishnah Shekalim/Hebrew/merged",
             @"Mishnah/Seder Moed/Mishnah Sukkah/English/merged",
             @"Mishnah/Seder Moed/Mishnah Sukkah/Hebrew/merged",
             @"Mishnah/Seder Moed/Mishnah Taanit/English/merged",
             @"Mishnah/Seder Moed/Mishnah Taanit/Hebrew/merged",
             @"Mishnah/Seder Moed/Mishnah Yoma/English/merged",
             @"Mishnah/Seder Moed/Mishnah Yoma/Hebrew/merged",
             @"Mishnah/Seder Nashim/Mishnah Gittin/English/merged",
             @"Mishnah/Seder Nashim/Mishnah Gittin/Hebrew/merged",
             @"Mishnah/Seder Nashim/Mishnah Ketubot/English/merged",
             @"Mishnah/Seder Nashim/Mishnah Ketubot/Hebrew/merged",
             @"Mishnah/Seder Nashim/Mishnah Kiddushin/English/merged",
             @"Mishnah/Seder Nashim/Mishnah Kiddushin/Hebrew/merged",
             @"Mishnah/Seder Nashim/Mishnah Nazir/English/merged",
             @"Mishnah/Seder Nashim/Mishnah Nazir/Hebrew/merged",
             @"Mishnah/Seder Nashim/Mishnah Nedarim/English/merged",
             @"Mishnah/Seder Nashim/Mishnah Nedarim/Hebrew/merged",
             @"Mishnah/Seder Nashim/Mishnah Sotah/English/merged",
             @"Mishnah/Seder Nashim/Mishnah Sotah/Hebrew/merged",
             @"Mishnah/Seder Nashim/Mishnah Yevamot/English/merged",
             @"Mishnah/Seder Nashim/Mishnah Yevamot/Hebrew/merged",
             @"Mishnah/Seder Nezikin/Mishnah Avodah Zarah/English/merged",
             @"Mishnah/Seder Nezikin/Mishnah Avodah Zarah/Hebrew/merged",
             @"Mishnah/Seder Nezikin/Mishnah Bava Batra/English/merged",
             @"Mishnah/Seder Nezikin/Mishnah Bava Batra/Hebrew/merged",
             @"Mishnah/Seder Nezikin/Mishnah Bava Kamma/English/merged",
             @"Mishnah/Seder Nezikin/Mishnah Bava Kamma/Hebrew/merged",
             @"Mishnah/Seder Nezikin/Mishnah Bava Metzia/English/merged",
             @"Mishnah/Seder Nezikin/Mishnah Bava Metzia/Hebrew/merged",
             @"Mishnah/Seder Nezikin/Mishnah Eduyot/English/merged",
             @"Mishnah/Seder Nezikin/Mishnah Eduyot/Hebrew/merged",
             @"Mishnah/Seder Nezikin/Mishnah Horayot/English/merged",
             @"Mishnah/Seder Nezikin/Mishnah Horayot/Hebrew/merged",
             @"Mishnah/Seder Nezikin/Mishnah Makkot/English/merged",
             @"Mishnah/Seder Nezikin/Mishnah Makkot/Hebrew/merged",
             @"Mishnah/Seder Nezikin/Mishnah Sanhedrin/English/merged",
             @"Mishnah/Seder Nezikin/Mishnah Sanhedrin/Hebrew/merged",
             @"Mishnah/Seder Nezikin/Mishnah Shevuot/English/merged",
             @"Mishnah/Seder Nezikin/Mishnah Shevuot/Hebrew/merged",
             @"Mishnah/Seder Nezikin/Pirkei Avot/English/merged",
             @"Mishnah/Seder Nezikin/Pirkei Avot/Hebrew/merged",
             @"Mishnah/Seder Tahorot/Mishnah Kelim/English/merged",
             @"Mishnah/Seder Tahorot/Mishnah Kelim/Hebrew/merged",
             @"Mishnah/Seder Tahorot/Mishnah Makhshirin/English/merged",
             @"Mishnah/Seder Tahorot/Mishnah Makhshirin/Hebrew/merged",
             @"Mishnah/Seder Tahorot/Mishnah Mikvaot/English/merged",
             @"Mishnah/Seder Tahorot/Mishnah Mikvaot/Hebrew/merged",
             @"Mishnah/Seder Tahorot/Mishnah Negaim/English/merged",
             @"Mishnah/Seder Tahorot/Mishnah Negaim/Hebrew/merged",
             @"Mishnah/Seder Tahorot/Mishnah Niddah/English/merged",
             @"Mishnah/Seder Tahorot/Mishnah Niddah/Hebrew/merged",
             @"Mishnah/Seder Tahorot/Mishnah Oholot/English/merged",
             @"Mishnah/Seder Tahorot/Mishnah Oholot/Hebrew/merged",
             @"Mishnah/Seder Tahorot/Mishnah Oktzin/English/merged",
             @"Mishnah/Seder Tahorot/Mishnah Oktzin/Hebrew/merged",
             @"Mishnah/Seder Tahorot/Mishnah Parah/English/merged",
             @"Mishnah/Seder Tahorot/Mishnah Parah/Hebrew/merged",
             @"Mishnah/Seder Tahorot/Mishnah Tahorot/English/merged",
             @"Mishnah/Seder Tahorot/Mishnah Tahorot/Hebrew/merged",
             @"Mishnah/Seder Tahorot/Mishnah Tevul Yom/English/merged",
             @"Mishnah/Seder Tahorot/Mishnah Tevul Yom/Hebrew/merged",
             @"Mishnah/Seder Tahorot/Mishnah Yadayim/English/merged",
             @"Mishnah/Seder Tahorot/Mishnah Yadayim/Hebrew/merged",
             @"Mishnah/Seder Tahorot/Mishnah Zavim/English/merged",
             @"Mishnah/Seder Tahorot/Mishnah Zavim/Hebrew/merged",
             @"Mishnah/Seder Zeraim/Mishnah Berakhot/English/merged",
             @"Mishnah/Seder Zeraim/Mishnah Berakhot/Hebrew/merged",
             @"Mishnah/Seder Zeraim/Mishnah Bikkurim/English/merged",
             @"Mishnah/Seder Zeraim/Mishnah Bikkurim/Hebrew/merged",
             @"Mishnah/Seder Zeraim/Mishnah Challah/English/merged",
             @"Mishnah/Seder Zeraim/Mishnah Challah/Hebrew/merged",
             @"Mishnah/Seder Zeraim/Mishnah Demai/English/merged",
             @"Mishnah/Seder Zeraim/Mishnah Demai/Hebrew/merged",
             @"Mishnah/Seder Zeraim/Mishnah Kilayim/English/merged",
             @"Mishnah/Seder Zeraim/Mishnah Kilayim/Hebrew/merged",
             @"Mishnah/Seder Zeraim/Mishnah Maaser Sheni/English/merged",
             @"Mishnah/Seder Zeraim/Mishnah Maaser Sheni/Hebrew/merged",
             @"Mishnah/Seder Zeraim/Mishnah Maasrot/English/merged",
             @"Mishnah/Seder Zeraim/Mishnah Maasrot/Hebrew/merged",
             @"Mishnah/Seder Zeraim/Mishnah Orlah/English/merged",
             @"Mishnah/Seder Zeraim/Mishnah Orlah/Hebrew/merged",
             @"Mishnah/Seder Zeraim/Mishnah Peah/English/merged",
             @"Mishnah/Seder Zeraim/Mishnah Peah/Hebrew/merged",
             @"Mishnah/Seder Zeraim/Mishnah Sheviit/English/merged",
             @"Mishnah/Seder Zeraim/Mishnah Sheviit/Hebrew/merged",
             @"Mishnah/Seder Zeraim/Mishnah Terumot/English/merged",
             @"Mishnah/Seder Zeraim/Mishnah Terumot/Hebrew/merged",
             
             @"Musar/Messilat Yesharim/English/merged",
             @"Musar/Messilat Yesharim/Hebrew/merged",
             @"Musar/Nefesh HaChaim/Hebrew/merged",
             @"Philosophy/Chovot Halevavot/English/merged",
             @"Philosophy/Derech Hashem/English/merged",
             @"Philosophy/Derech Hashem/Hebrew/merged",
             @"Philosophy/Duties of the Heart/English/merged",
             @"Philosophy/Eight Chapters/English/merged",
             @"Philosophy/Eight Chapters/Hebrew/merged",
             @"Philosophy/Ein Ayah/Hebrew/merged",
             @"Philosophy/For the Perplexed of the Generation/English/merged",
             @"Philosophy/For the Perplexed of the Generation/Hebrew/merged",
             @"Philosophy/Guide for the Perplexed/English/merged",
             @"Philosophy/Guide for the Perplexed/Hebrew/merged",
             @"Philosophy/Kad HaKemach/English/merged",
             @"Philosophy/Netivot Olam/English/merged",
             @"Philosophy/Netivot Olam/Hebrew/merged",
             @"Philosophy/Orot HaKodesh/Hebrew/merged",
             @"Philosophy/Sefer Kuzari/English/merged",
             @"Philosophy/Sefer Kuzari/Hebrew/merged",
             @"Philosophy/Shmonah Kevatzim/Hebrew/merged",
             @"Talmud/Bavli/Seder Kodashim/Arakhin/Hebrew/merged",
             @"Talmud/Bavli/Seder Kodashim/Bekhorot/Hebrew/merged",
             @"Talmud/Bavli/Seder Kodashim/Chullin/English/merged",
             @"Talmud/Bavli/Seder Kodashim/Chullin/Hebrew/merged",
             @"Talmud/Bavli/Seder Kodashim/Keritot/English/merged",
             @"Talmud/Bavli/Seder Kodashim/Keritot/Hebrew/merged",
             @"Talmud/Bavli/Seder Kodashim/Meilah/Hebrew/merged",
             @"Talmud/Bavli/Seder Kodashim/Menachot/Hebrew/merged",
             @"Talmud/Bavli/Seder Kodashim/Tamid/Hebrew/merged",
             @"Talmud/Bavli/Seder Kodashim/Temurah/Hebrew/merged",
             @"Talmud/Bavli/Seder Kodashim/Zevachim/Hebrew/merged",
             @"Talmud/Bavli/Seder Moed/Beitzah/English/merged",
             @"Talmud/Bavli/Seder Moed/Beitzah/Hebrew/merged",
             @"Talmud/Bavli/Seder Moed/Chagigah/English/merged",
             @"Talmud/Bavli/Seder Moed/Chagigah/Hebrew/merged",
             @"Talmud/Bavli/Seder Moed/Eruvin/English/merged",
             @"Talmud/Bavli/Seder Moed/Eruvin/Hebrew/merged",
             @"Talmud/Bavli/Seder Moed/Megillah/English/merged",
             @"Talmud/Bavli/Seder Moed/Megillah/Hebrew/merged",
             @"Talmud/Bavli/Seder Moed/Moed Katan/Hebrew/merged",
             @"Talmud/Bavli/Seder Moed/Pesachim/English/merged",
             @"Talmud/Bavli/Seder Moed/Pesachim/Hebrew/merged",
             @"Talmud/Bavli/Seder Moed/Rosh Hashanah/English/merged",
             @"Talmud/Bavli/Seder Moed/Rosh Hashanah/Hebrew/merged",
             @"Talmud/Bavli/Seder Moed/Shabbat/English/merged",
             @"Talmud/Bavli/Seder Moed/Shabbat/Hebrew/merged",
             @"Talmud/Bavli/Seder Moed/Sukkah/English/merged",
             @"Talmud/Bavli/Seder Moed/Sukkah/Hebrew/merged",
             @"Talmud/Bavli/Seder Moed/Taanit/English/merged",
             @"Talmud/Bavli/Seder Moed/Taanit/Hebrew/merged",
             @"Talmud/Bavli/Seder Moed/Yoma/English/merged",
             @"Talmud/Bavli/Seder Moed/Yoma/Hebrew/merged",
             @"Talmud/Bavli/Seder Nashim/Gittin/English/merged",
             @"Talmud/Bavli/Seder Nashim/Gittin/Hebrew/merged",
             @"Talmud/Bavli/Seder Nashim/Ketubot/English/merged",
             @"Talmud/Bavli/Seder Nashim/Ketubot/Hebrew/merged",
             @"Talmud/Bavli/Seder Nashim/Kiddushin/English/merged",
             @"Talmud/Bavli/Seder Nashim/Kiddushin/Hebrew/merged",
             @"Talmud/Bavli/Seder Nashim/Nazir/Hebrew/merged",
             @"Talmud/Bavli/Seder Nashim/Nedarim/English/merged",
             @"Talmud/Bavli/Seder Nashim/Nedarim/Hebrew/merged",
             @"Talmud/Bavli/Seder Nashim/Sotah/English/merged",
             @"Talmud/Bavli/Seder Nashim/Sotah/Hebrew/merged",
             @"Talmud/Bavli/Seder Nashim/Yevamot/English/merged",
             @"Talmud/Bavli/Seder Nashim/Yevamot/Hebrew/merged",
             @"Talmud/Bavli/Seder Nezikin/Avodah Zarah/English/merged",
             @"Talmud/Bavli/Seder Nezikin/Avodah Zarah/Hebrew/merged",
             @"Talmud/Bavli/Seder Nezikin/Bava Batra/English/merged",
             @"Talmud/Bavli/Seder Nezikin/Bava Batra/Hebrew/merged",
             @"Talmud/Bavli/Seder Nezikin/Bava Kamma/English/merged",
             @"Talmud/Bavli/Seder Nezikin/Bava Kamma/Hebrew/merged",
             @"Talmud/Bavli/Seder Nezikin/Bava Metzia/English/merged",
             @"Talmud/Bavli/Seder Nezikin/Bava Metzia/Hebrew/merged",
             @"Talmud/Bavli/Seder Nezikin/Horayot/English/merged",
             @"Talmud/Bavli/Seder Nezikin/Horayot/Hebrew/merged",
             @"Talmud/Bavli/Seder Nezikin/Makkot/English/merged",
             @"Talmud/Bavli/Seder Nezikin/Makkot/Hebrew/merged",
             @"Talmud/Bavli/Seder Nezikin/Sanhedrin/English/merged",
             @"Talmud/Bavli/Seder Nezikin/Sanhedrin/Hebrew/merged",
             @"Talmud/Bavli/Seder Nezikin/Shevuot/English/merged",
             @"Talmud/Bavli/Seder Nezikin/Shevuot/Hebrew/merged",
             @"Talmud/Bavli/Seder Tahorot/Niddah/Hebrew/merged",
             @"Talmud/Bavli/Seder Zeraim/Berakhot/English/merged",
             @"Talmud/Bavli/Seder Zeraim/Berakhot/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Beitzah/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Chagigah/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Eiruvin/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Megillah/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Moed Kattan/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Pesachim/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Rosh Hashanah/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Shabbat/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Shekalim/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Sukkah/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Ta'anit/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Yoma/English/merged",
             @"Talmud/Yerushalmi/Seder Moed/Jerusalem Talmud Yoma/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Nashim/Jerusalem Talmud Gittin/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Nashim/Jerusalem Talmud Ketubot/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Nashim/Jerusalem Talmud Kiddushin/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Nashim/Jerusalem Talmud Nazir/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Nashim/Jerusalem Talmud Nedarim/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Nashim/Jerusalem Talmud Sotah/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Nashim/Jerusalem Talmud Yevamot/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Nezikin/Jerusalem Talmud Avodah Zarah/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Nezikin/Jerusalem Talmud Bava Batra/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Nezikin/Jerusalem Talmud Bava Kamma/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Nezikin/Jerusalem Talmud Bava Metsia/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Nezikin/Jerusalem Talmud Horayot/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Nezikin/Jerusalem Talmud Makkot/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Nezikin/Jerusalem Talmud Sanhedrin/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Nezikin/Jerusalem Talmud Shevuot/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Tahorot/Jerusalem Talmud Niddah/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Berakhot/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Bikkurim/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Demai/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Hallah/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Kilayim/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Ma'aser Sheni/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Ma'asrot/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Orlah/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Peah/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Shevi'it/Hebrew/merged",
             @"Talmud/Yerushalmi/Seder Zeraim/Jerusalem Talmud Terumot/Hebrew/merged",
             
             @"Tanach/Prophets/Amos/English/merged",
             @"Tanach/Prophets/Amos/Hebrew/merged",
             @"Tanach/Prophets/Ezekiel/English/merged",
             @"Tanach/Prophets/Ezekiel/Hebrew/merged",
             @"Tanach/Prophets/Habakkuk/English/merged",
             @"Tanach/Prophets/Habakkuk/Hebrew/merged",
             @"Tanach/Prophets/Haggai/English/merged",
             @"Tanach/Prophets/Haggai/Hebrew/merged",
             @"Tanach/Prophets/Hosea/English/merged",
             @"Tanach/Prophets/Hosea/Hebrew/merged",
             @"Tanach/Prophets/I Kings/English/merged",
             @"Tanach/Prophets/I Kings/Hebrew/merged",
             @"Tanach/Prophets/I Samuel/English/merged",
             @"Tanach/Prophets/I Samuel/Hebrew/merged",
             @"Tanach/Prophets/II Kings/English/merged",
             @"Tanach/Prophets/II Kings/Hebrew/merged",
             @"Tanach/Prophets/II Samuel/English/merged",
             @"Tanach/Prophets/II Samuel/Hebrew/merged",
             @"Tanach/Prophets/Isaiah/English/merged",
             @"Tanach/Prophets/Isaiah/Hebrew/merged",
             @"Tanach/Prophets/Jeremiah/English/merged",
             @"Tanach/Prophets/Jeremiah/Hebrew/merged",
             @"Tanach/Prophets/Joel/English/merged",
             @"Tanach/Prophets/Joel/Hebrew/merged",
             @"Tanach/Prophets/Jonah/English/merged",
             @"Tanach/Prophets/Jonah/Hebrew/merged",
             @"Tanach/Prophets/Joshua/English/merged",
             @"Tanach/Prophets/Joshua/Hebrew/merged",
             @"Tanach/Prophets/Judges/English/merged",
             @"Tanach/Prophets/Judges/Hebrew/merged",
             @"Tanach/Prophets/Malachi/English/merged",
             @"Tanach/Prophets/Malachi/Hebrew/merged",
             @"Tanach/Prophets/Micah/English/merged",
             @"Tanach/Prophets/Micah/Hebrew/merged",
             @"Tanach/Prophets/Nahum/English/merged",
             @"Tanach/Prophets/Nahum/Hebrew/merged",
             @"Tanach/Prophets/Obadiah/English/merged",
             @"Tanach/Prophets/Obadiah/Hebrew/merged",
             @"Tanach/Prophets/Zechariah/English/merged",
             @"Tanach/Prophets/Zechariah/Hebrew/merged",
             @"Tanach/Prophets/Zephaniah/English/merged",
             @"Tanach/Prophets/Zephaniah/Hebrew/merged",
             @"Tanach/Targum/Aramaic Targum to Song of Songs/English/merged",
             @"Tanach/Targum/Onkelos Deuteronomy/Hebrew/merged",
             @"Tanach/Targum/Onkelos Exodus/Hebrew/merged",
             @"Tanach/Targum/Onkelos Genesis/English/merged",
             @"Tanach/Targum/Onkelos Genesis/Hebrew/merged",
             @"Tanach/Targum/Onkelos Leviticus/Hebrew/merged",
             @"Tanach/Targum/Onkelos Numbers/English/merged",
             @"Tanach/Targum/Onkelos Numbers/Hebrew/merged",
             @"Tanach/Targum/Targum Jonathan on Deuteronomy/English/merged",
             @"Tanach/Targum/Targum Jonathan on Deuteronomy/Hebrew/merged",
             @"Tanach/Targum/Targum Jonathan on Exodus/English/merged",
             @"Tanach/Targum/Targum Jonathan on Exodus/Hebrew/merged",
             @"Tanach/Targum/Targum Jonathan on Genesis/Hebrew/merged",
             @"Tanach/Targum/Targum Jonathan on Leviticus/Hebrew/merged",
             @"Tanach/Targum/Targum Jonathan on Numbers/English/merged",
             @"Tanach/Targum/Targum Jonathan on Numbers/Hebrew/merged",
             @"Tanach/Torah/Deuteronomy/English/merged",
             @"Tanach/Torah/Deuteronomy/Hebrew/merged",
             @"Tanach/Torah/Exodus/English/merged",
             @"Tanach/Torah/Exodus/Hebrew/merged",
             @"Tanach/Torah/Genesis/English/merged",
             @"Tanach/Torah/Genesis/Hebrew/merged",
             @"Tanach/Torah/Leviticus/English/merged",
             @"Tanach/Torah/Leviticus/Hebrew/merged",
             @"Tanach/Torah/Numbers/English/merged",
             @"Tanach/Torah/Numbers/Hebrew/merged",
             @"Tanach/Writings/Daniel/English/merged",
             @"Tanach/Writings/Daniel/Hebrew/merged",
             @"Tanach/Writings/Ecclesiastes/English/merged",
             @"Tanach/Writings/Ecclesiastes/Hebrew/merged",
             @"Tanach/Writings/Esther/English/merged",
             @"Tanach/Writings/Esther/Hebrew/merged",
             @"Tanach/Writings/Ezra/English/merged",
             @"Tanach/Writings/Ezra/Hebrew/merged",
             @"Tanach/Writings/I Chronicles/English/merged",
             @"Tanach/Writings/I Chronicles/Hebrew/merged",
             @"Tanach/Writings/II Chronicles/English/merged",
             @"Tanach/Writings/II Chronicles/Hebrew/merged",
             @"Tanach/Writings/Job/English/merged",
             @"Tanach/Writings/Job/Hebrew/merged",
             @"Tanach/Writings/Lamentations/English/merged",
             @"Tanach/Writings/Lamentations/Hebrew/merged",
             @"Tanach/Writings/Nehemiah/English/merged",
             @"Tanach/Writings/Nehemiah/Hebrew/merged",
             @"Tanach/Writings/Proverbs/English/merged",
             @"Tanach/Writings/Proverbs/Hebrew/merged",
             @"Tanach/Writings/Psalms/English/merged",
             @"Tanach/Writings/Psalms/Hebrew/merged",
             @"Tanach/Writings/Ruth/English/merged",
             @"Tanach/Writings/Ruth/Hebrew/merged",
             @"Tanach/Writings/Song of Songs/English/merged",
             @"Tanach/Writings/Song of Songs/Hebrew/merged",
             
             @"Tosefta/Seder Kodashim/Tosefta Arakhin/Hebrew/merged",
             @"Tosefta/Seder Kodashim/Tosefta Bekhorot/Hebrew/merged",
             @"Tosefta/Seder Kodashim/Tosefta Chullin/Hebrew/merged",
             @"Tosefta/Seder Kodashim/Tosefta Keritot/Hebrew/merged",
             @"Tosefta/Seder Kodashim/Tosefta Meilah/Hebrew/merged",
             @"Tosefta/Seder Kodashim/Tosefta Menahot/Hebrew/merged",
             @"Tosefta/Seder Kodashim/Tosefta Temurah/Hebrew/merged",
             @"Tosefta/Seder Kodashim/Tosefta Zevahim/Hebrew/merged",
             @"Tosefta/Seder Moed/Tosefta Beitsah/English/merged",
             @"Tosefta/Seder Moed/Tosefta Beitsah/Hebrew/merged",
             @"Tosefta/Seder Moed/Tosefta Chagigah/Hebrew/merged",
             @"Tosefta/Seder Moed/Tosefta Eiruvin/Hebrew/merged",
             @"Tosefta/Seder Moed/Tosefta Megillah/Hebrew/merged",
             @"Tosefta/Seder Moed/Tosefta Moed Kattan/Hebrew/merged",
             @"Tosefta/Seder Moed/Tosefta Pesachim/Hebrew/merged",
             @"Tosefta/Seder Moed/Tosefta Rosh HaShanah/English/merged",
             @"Tosefta/Seder Moed/Tosefta Rosh HaShanah/Hebrew/merged",
             @"Tosefta/Seder Moed/Tosefta Shabbat/English/merged",
             @"Tosefta/Seder Moed/Tosefta Shabbat/Hebrew/merged",
             @"Tosefta/Seder Moed/Tosefta Shekalim/Hebrew/merged",
             @"Tosefta/Seder Moed/Tosefta Sukkah/English/merged",
             @"Tosefta/Seder Moed/Tosefta Sukkah/Hebrew/merged",
             @"Tosefta/Seder Moed/Tosefta Ta'anit/Hebrew/merged",
             @"Tosefta/Seder Moed/Tosefta Yoma/Hebrew/merged",
             @"Tosefta/Seder Nashim/Tosefta Gittin/Hebrew/merged",
             @"Tosefta/Seder Nashim/Tosefta Ketubot/Hebrew/merged",
             @"Tosefta/Seder Nashim/Tosefta Kiddushin/Hebrew/merged",
             @"Tosefta/Seder Nashim/Tosefta Nazir/Hebrew/merged",
             @"Tosefta/Seder Nashim/Tosefta Nedarim/Hebrew/merged",
             @"Tosefta/Seder Nashim/Tosefta Sotah/English/merged",
             @"Tosefta/Seder Nashim/Tosefta Sotah/Hebrew/merged",
             @"Tosefta/Seder Nashim/Tosefta Yevamot/Hebrew/merged",
             @"Tosefta/Seder Nezikin/Tosefta Avodah Zarah/Hebrew/merged",
             @"Tosefta/Seder Nezikin/Tosefta Bava Batra/Hebrew/merged",
             @"Tosefta/Seder Nezikin/Tosefta Bava Kamma/Hebrew/merged",
             @"Tosefta/Seder Nezikin/Tosefta Bava Metzia/English/merged",
             @"Tosefta/Seder Nezikin/Tosefta Bava Metzia/Hebrew/merged",
             @"Tosefta/Seder Nezikin/Tosefta Eduyot/Hebrew/merged",
             @"Tosefta/Seder Nezikin/Tosefta Horayot/Hebrew/merged",
             @"Tosefta/Seder Nezikin/Tosefta Makkot/Hebrew/merged",
             @"Tosefta/Seder Nezikin/Tosefta Sanhedrin/Hebrew/merged",
             @"Tosefta/Seder Nezikin/Tosefta Shevuot/Hebrew/merged",
             @"Tosefta/Seder Toharot/Tosefta Keilim Batra/Hebrew/merged",
             @"Tosefta/Seder Toharot/Tosefta Keilim Kamma/Hebrew/merged",
             @"Tosefta/Seder Toharot/Tosefta Keilim Metsia/English/merged",
             @"Tosefta/Seder Toharot/Tosefta Keilim Metsia/Hebrew/merged",
             @"Tosefta/Seder Toharot/Tosefta Makhshirin/Hebrew/merged",
             @"Tosefta/Seder Toharot/Tosefta Mikvaot/Hebrew/merged",
             @"Tosefta/Seder Toharot/Tosefta Negaim/Hebrew/merged",
             @"Tosefta/Seder Toharot/Tosefta Niddah/Hebrew/merged",
             @"Tosefta/Seder Toharot/Tosefta Ohalot/Hebrew/merged",
             @"Tosefta/Seder Toharot/Tosefta Parah/Hebrew/merged",
             @"Tosefta/Seder Toharot/Tosefta Tevul Yom/Hebrew/merged",
             @"Tosefta/Seder Toharot/Tosefta Tohorot/Hebrew/merged",
             @"Tosefta/Seder Toharot/Tosefta Uktsin/Hebrew/merged",
             @"Tosefta/Seder Toharot/Tosefta Yadayim/Hebrew/merged",
             @"Tosefta/Seder Toharot/Tosefta Zavim/Hebrew/merged",
             @"Tosefta/Seder Zeraim/Tosefta Berakhot/English/merged",
             @"Tosefta/Seder Zeraim/Tosefta Berakhot/Hebrew/merged",
             @"Tosefta/Seder Zeraim/Tosefta Bikkurim/Hebrew/merged",
             @"Tosefta/Seder Zeraim/Tosefta Challah/Hebrew/merged",
             @"Tosefta/Seder Zeraim/Tosefta Demai/Hebrew/merged",
             @"Tosefta/Seder Zeraim/Tosefta Kilaim/Hebrew/merged",
             @"Tosefta/Seder Zeraim/Tosefta Kilayim /Hebrew/merged",
             @"Tosefta/Seder Zeraim/Tosefta Ma'aser Sheni/Hebrew/merged",
             @"Tosefta/Seder Zeraim/Tosefta Ma'asrot/Hebrew/merged",
             @"Tosefta/Seder Zeraim/Tosefta Orlah/Hebrew/merged",
             @"Tosefta/Seder Zeraim/Tosefta Peah/English/merged",
             @"Tosefta/Seder Zeraim/Tosefta Peah/Hebrew/merged",
             @"Tosefta/Seder Zeraim/Tosefta Shevi'it/Hebrew/merged",
             @"Tosefta/Seder Zeraim/Tosefta Terumot/Hebrew/merged"
             ];
}



@end
